// 本文件由 scripts/getEnv.ts 自动生成
// @generated 请勿手工编辑。
// 生成时间: 2026-01-29T16:01:50.288Z

export const GLOBAL_VAR_OFFSET = 1073741824
export const ARGUMENT_VAR_OFFSET = 536870912
export const ARG_SCOPE_INDEX = 1
export const ARG_SCOPE_END = -2
export const DEBUG_SCOPE_INDEX = -3
export const JS_MAX_LOCAL_VARS = 65534
export const JS_STACK_SIZE_MAX = 65534

// 基于 compileOptions 推导的常量
export const COMPILE_OPTIONS = 5
export const SHORT_OPCODES = true
export const JS_MODE_STRICT_DEFAULT = 1
export const BYTECODE_VERSION = 5
export const FIRST_ATOM_ID = 228

// QuickJS 常量（来自 QuickJS 头文件；用于 TS 侧对齐与消除魔数）
// third_party/QuickJS/include/QuickJS/quickjs.h:61-62
export const JS_PROP_CONFIGURABLE = 1
export const JS_PROP_WRITABLE = 2
// third_party/QuickJS/include/QuickJS/quickjs.h:96-103
export const JS_EVAL_TYPE_GLOBAL = 0
export const JS_EVAL_TYPE_MODULE = 1
export const JS_EVAL_TYPE_DIRECT = 2
export const JS_EVAL_TYPE_INDIRECT = 3
export const JS_EVAL_TYPE_MASK = 3
// third_party/QuickJS/src/core/function.h:40-44
export const JS_THROW_VAR_RO = 0
export const JS_THROW_VAR_REDECL = 1
export const JS_THROW_VAR_UNINITIALIZED = 2
// third_party/QuickJS/src/core/function.h:34-38
export const OP_DEFINE_METHOD_METHOD = 0
export const OP_DEFINE_METHOD_GETTER = 1
export const OP_DEFINE_METHOD_SETTER = 2
export const OP_DEFINE_METHOD_ENUMERABLE = 4
// third_party/QuickJS/src/core/runtime.h:50-51
export const DEFINE_GLOBAL_LEX_VAR = 128
export const DEFINE_GLOBAL_FUNC_VAR = 64
// third_party/QuickJS/src/core/exception.h:32
export const JS_DEFINE_CLASS_HAS_HERITAGE = 1
// third_party/QuickJS/include/QuickJS/quickjs.h:237
export const JS_ATOM_NULL = 0

// QuickJS 编译器实现细节常量（来自 QuickJS parser.c；用于 TS 侧对齐与消除魔数）
// third_party/QuickJS/src/core/parser.c:12248-12252 (compute_stack_size: stack_level_tab 初始化为 0xffff)
export const STACK_LEVEL_UNSET = 65535
// QuickJS 字节码 op 数量上限（compute_stack_size 中用于校验）
export const OP_COUNT = 256
// third_party/QuickJS/src/core/parser.c:6900-6905 (js_parse_for_in_of: OP_for_of_next 的默认操作数)
export const FOR_OF_NEXT_OPERAND_DEFAULT = 0

// QuickJS 字节码格式常量（来自 QuickJS bytecode.cpp；用于读写 .qbc 时对齐与消除魔数）
// third_party/QuickJS/src/core/bytecode.cpp:448-461 (bc_set_flags: flags bit layout)
export const JS_FUNCTION_BYTECODE_FLAG_HAS_DEBUG = 1024

export enum CompileFlags {
  COMPILE_FLAG_NONE = 0,
  COMPILE_FLAG_DUMP = 1,
  COMPILE_FLAG_BIGNUM = 2,
  COMPILE_FLAG_SHORT_OPCODES = 4,
}

export enum PutLValueEnum {
  PUT_LVALUE_NOKEEP = 0,
  PUT_LVALUE_NOKEEP_DEPTH = 1,
  PUT_LVALUE_KEEP_TOP = 2,
  PUT_LVALUE_KEEP_SECOND = 3,
  PUT_LVALUE_NOKEEP_BOTTOM = 4,
}

export enum BytecodeTag {
  TC_TAG_NULL = 1,
  TC_TAG_UNDEFINED = 2,
  TC_TAG_BOOL_FALSE = 3,
  TC_TAG_BOOL_TRUE = 4,
  TC_TAG_INT32 = 5,
  TC_TAG_FLOAT64 = 6,
  TC_TAG_STRING = 7,
  TC_TAG_OBJECT = 8,
  TC_TAG_ARRAY = 9,
  TC_TAG_BIG_INT = 10,
  TC_TAG_TEMPLATE_OBJECT = 11,
  TC_TAG_FUNCTION_BYTECODE = 12,
  TC_TAG_MODULE = 13,
  TC_TAG_TYPED_ARRAY = 14,
  TC_TAG_ARRAY_BUFFER = 15,
  TC_TAG_SHARED_ARRAY_BUFFER = 16,
  TC_TAG_DATE = 17,
  TC_TAG_OBJECT_VALUE = 18,
  TC_TAG_OBJECT_REFERENCE = 19,
}

export enum FunctionKind {
  JS_FUNC_NORMAL = 0,
  JS_FUNC_GENERATOR = 1,
  JS_FUNC_ASYNC = 2,
  JS_FUNC_ASYNC_GENERATOR = 3,
}

export enum JSMode {
  JS_MODE_STRICT = 1,
  JS_MODE_ASYNC = 4,
  JS_MODE_BACKTRACE_BARRIER = 8,
}

export enum PC2Line {
  PC2LINE_BASE = -1,
  PC2LINE_RANGE = 5,
  PC2LINE_OP_FIRST = 1,
  PC2LINE_DIFF_PC_MAX = 50,
}

export enum JSParseFunctionEnum {
  JS_PARSE_FUNC_STATEMENT = 0,
  JS_PARSE_FUNC_VAR = 1,
  JS_PARSE_FUNC_EXPR = 2,
  JS_PARSE_FUNC_ARROW = 3,
  JS_PARSE_FUNC_GETTER = 4,
  JS_PARSE_FUNC_SETTER = 5,
  JS_PARSE_FUNC_METHOD = 6,
  JS_PARSE_FUNC_CLASS_STATIC_INIT = 7,
  JS_PARSE_FUNC_CLASS_CONSTRUCTOR = 8,
  JS_PARSE_FUNC_DERIVED_CLASS_CONSTRUCTOR = 9,
}

export enum JSParseExportEnum {
  JS_PARSE_EXPORT_NONE = 0,
  JS_PARSE_EXPORT_NAMED = 1,
  JS_PARSE_EXPORT_DEFAULT = 2,
}

export enum JSVarKindEnum {
  JS_VAR_NORMAL = 0,
  JS_VAR_FUNCTION_DECL = 1,
  JS_VAR_NEW_FUNCTION_DECL = 2,
  JS_VAR_CATCH = 3,
  JS_VAR_FUNCTION_NAME = 4,
  JS_VAR_PRIVATE_FIELD = 5,
  JS_VAR_PRIVATE_METHOD = 6,
  JS_VAR_PRIVATE_GETTER = 7,
  JS_VAR_PRIVATE_SETTER = 8,
  JS_VAR_PRIVATE_GETTER_SETTER = 9,
}

export enum OPSpecialObjectEnum {
  OP_SPECIAL_OBJECT_ARGUMENTS = 0,
  OP_SPECIAL_OBJECT_MAPPED_ARGUMENTS = 1,
  OP_SPECIAL_OBJECT_THIS_FUNC = 2,
  OP_SPECIAL_OBJECT_NEW_TARGET = 3,
  OP_SPECIAL_OBJECT_HOME_OBJECT = 4,
  OP_SPECIAL_OBJECT_VAR_OBJECT = 5,
  OP_SPECIAL_OBJECT_IMPORT_META = 6,
}

export enum OpFormat {
  none = 0,
  none_int = 1,
  none_loc = 2,
  none_arg = 3,
  none_var_ref = 4,
  u8 = 5,
  i8 = 6,
  loc8 = 7,
  const8 = 8,
  label8 = 9,
  u16 = 10,
  i16 = 11,
  label16 = 12,
  npop = 13,
  npopx = 14,
  npop_u16 = 15,
  loc = 16,
  arg = 17,
  var_ref = 18,
  u32 = 19,
  i32 = 20,
  const = 21,
  label = 22,
  atom = 23,
  atom_u8 = 24,
  atom_u16 = 25,
  atom_label_u8 = 26,
  atom_label_u16 = 27,
  label_u16 = 28,
}

// copy_data_properties flags 编码（对齐 QuickJS parser.c 的 emit_u8 公式）
export const TEMP_OPCODE_MIN = 182
export const TEMP_OPCODE_MAX = 200
export function encodeCopyDataPropertiesFlags(depthLValue: number): number {
  return 0 | ((depthLValue + 1) << 2) | ((depthLValue + 2) << 5)
}
export const COPY_DATA_PROPERTIES_FLAGS_DEPTH0 = encodeCopyDataPropertiesFlags(0)

// OP_copy_data_properties 的 u8 操作数编码（对齐 QuickJS parser.c）
// - 对象字面量展开 { ...obj }：parser.c:2947-2952
// - 解构 rest 属性 {a, ...rest}：parser.c:4386-4388
export const COPY_DATA_PROPERTIES_EXCLUDE_FIRST_SHIFT = 2
export const COPY_DATA_PROPERTIES_EXCLUDE_SECOND_SHIFT = 5
export function encodeCopyDataPropertiesOperand(copyFlags: number, excludeFirstIdx: number, excludeSecondIdx: number): number {
  return (copyFlags & 0x03) | ((excludeFirstIdx & 0x07) << COPY_DATA_PROPERTIES_EXCLUDE_FIRST_SHIFT) | ((excludeSecondIdx & 0x07) << COPY_DATA_PROPERTIES_EXCLUDE_SECOND_SHIFT)
}
// QuickJS object spread: emit_u8(s, 2 | (1 << 2) | (0 << 5));
export const COPY_DATA_PROPERTIES_OPERAND_SPREAD = encodeCopyDataPropertiesOperand(2, 1, 0)

export enum Opcode {
  OP_invalid = 0,
  OP_push_i32 = 1,
  OP_push_const = 2,
  OP_fclosure = 3,
  OP_push_atom_value = 4,
  OP_private_symbol = 5,
  OP_undefined = 6,
  OP_null = 7,
  OP_push_this = 8,
  OP_push_false = 9,
  OP_push_true = 10,
  OP_object = 11,
  OP_special_object = 12,
  OP_rest = 13,
  OP_drop = 14,
  OP_nip = 15,
  OP_nip1 = 16,
  OP_dup = 17,
  OP_dup1 = 18,
  OP_dup2 = 19,
  OP_dup3 = 20,
  OP_insert2 = 21,
  OP_insert3 = 22,
  OP_insert4 = 23,
  OP_perm3 = 24,
  OP_perm4 = 25,
  OP_perm5 = 26,
  OP_swap = 27,
  OP_swap2 = 28,
  OP_rot3l = 29,
  OP_rot3r = 30,
  OP_rot4l = 31,
  OP_rot5l = 32,
  OP_call_constructor = 33,
  OP_call = 34,
  OP_tail_call = 35,
  OP_call_method = 36,
  OP_tail_call_method = 37,
  OP_array_from = 38,
  OP_apply = 39,
  OP_return = 40,
  OP_return_undef = 41,
  OP_check_ctor_return = 42,
  OP_check_ctor = 43,
  OP_init_ctor = 44,
  OP_check_brand = 45,
  OP_add_brand = 46,
  OP_return_async = 47,
  OP_throw = 48,
  OP_throw_error = 49,
  OP_eval = 50,
  OP_apply_eval = 51,
  OP_regexp = 52,
  OP_get_super = 53,
  OP_import = 54,
  OP_check_var = 55,
  OP_get_var_undef = 56,
  OP_get_var = 57,
  OP_put_var = 58,
  OP_put_var_init = 59,
  OP_put_var_strict = 60,
  OP_get_ref_value = 61,
  OP_put_ref_value = 62,
  OP_define_var = 63,
  OP_check_define_var = 64,
  OP_define_func = 65,
  OP_get_field = 66,
  OP_get_field2 = 67,
  OP_put_field = 68,
  OP_get_private_field = 69,
  OP_put_private_field = 70,
  OP_define_private_field = 71,
  OP_get_array_el = 72,
  OP_get_array_el2 = 73,
  OP_get_array_el3 = 74,
  OP_put_array_el = 75,
  OP_get_super_value = 76,
  OP_put_super_value = 77,
  OP_define_field = 78,
  OP_set_name = 79,
  OP_set_name_computed = 80,
  OP_set_proto = 81,
  OP_set_home_object = 82,
  OP_define_array_el = 83,
  OP_append = 84,
  OP_copy_data_properties = 85,
  OP_define_method = 86,
  OP_define_method_computed = 87,
  OP_define_class = 88,
  OP_define_class_computed = 89,
  OP_get_loc = 90,
  OP_put_loc = 91,
  OP_set_loc = 92,
  OP_get_arg = 93,
  OP_put_arg = 94,
  OP_set_arg = 95,
  OP_get_var_ref = 96,
  OP_put_var_ref = 97,
  OP_set_var_ref = 98,
  OP_set_loc_uninitialized = 99,
  OP_get_loc_check = 100,
  OP_put_loc_check = 101,
  OP_put_loc_check_init = 102,
  OP_get_loc_checkthis = 103,
  OP_get_var_ref_check = 104,
  OP_put_var_ref_check = 105,
  OP_put_var_ref_check_init = 106,
  OP_close_loc = 107,
  OP_if_false = 108,
  OP_if_true = 109,
  OP_goto = 110,
  OP_catch = 111,
  OP_gosub = 112,
  OP_ret = 113,
  OP_nip_catch = 114,
  OP_to_object = 115,
  OP_to_propkey = 116,
  OP_with_get_var = 117,
  OP_with_put_var = 118,
  OP_with_delete_var = 119,
  OP_with_make_ref = 120,
  OP_with_get_ref = 121,
  OP_make_loc_ref = 122,
  OP_make_arg_ref = 123,
  OP_make_var_ref_ref = 124,
  OP_make_var_ref = 125,
  OP_for_in_start = 126,
  OP_for_of_start = 127,
  OP_for_await_of_start = 128,
  OP_for_in_next = 129,
  OP_for_of_next = 130,
  OP_for_await_of_next = 131,
  OP_iterator_check_object = 132,
  OP_iterator_get_value_done = 133,
  OP_iterator_close = 134,
  OP_iterator_next = 135,
  OP_iterator_call = 136,
  OP_initial_yield = 137,
  OP_yield = 138,
  OP_yield_star = 139,
  OP_async_yield_star = 140,
  OP_await = 141,
  OP_neg = 142,
  OP_plus = 143,
  OP_dec = 144,
  OP_inc = 145,
  OP_post_dec = 146,
  OP_post_inc = 147,
  OP_dec_loc = 148,
  OP_inc_loc = 149,
  OP_add_loc = 150,
  OP_not = 151,
  OP_lnot = 152,
  OP_typeof = 153,
  OP_delete = 154,
  OP_delete_var = 155,
  OP_mul = 156,
  OP_div = 157,
  OP_mod = 158,
  OP_add = 159,
  OP_sub = 160,
  OP_pow = 161,
  OP_shl = 162,
  OP_sar = 163,
  OP_shr = 164,
  OP_lt = 165,
  OP_lte = 166,
  OP_gt = 167,
  OP_gte = 168,
  OP_instanceof = 169,
  OP_in = 170,
  OP_eq = 171,
  OP_neq = 172,
  OP_strict_eq = 173,
  OP_strict_neq = 174,
  OP_and = 175,
  OP_xor = 176,
  OP_or = 177,
  OP_is_undefined_or_null = 178,
  OP_private_in = 179,
  OP_push_bigint_i32 = 180,
  OP_nop = 181,
  OP_push_minus1 = 182,
  OP_push_0 = 183,
  OP_push_1 = 184,
  OP_push_2 = 185,
  OP_push_3 = 186,
  OP_push_4 = 187,
  OP_push_5 = 188,
  OP_push_6 = 189,
  OP_push_7 = 190,
  OP_push_i8 = 191,
  OP_push_i16 = 192,
  OP_push_const8 = 193,
  OP_fclosure8 = 194,
  OP_push_empty_string = 195,
  OP_get_loc8 = 196,
  OP_put_loc8 = 197,
  OP_set_loc8 = 198,
  OP_get_loc0 = 199,
  OP_get_loc1 = 200,
  OP_get_loc2 = 201,
  OP_get_loc3 = 202,
  OP_put_loc0 = 203,
  OP_put_loc1 = 204,
  OP_put_loc2 = 205,
  OP_put_loc3 = 206,
  OP_set_loc0 = 207,
  OP_set_loc1 = 208,
  OP_set_loc2 = 209,
  OP_set_loc3 = 210,
  OP_get_arg0 = 211,
  OP_get_arg1 = 212,
  OP_get_arg2 = 213,
  OP_get_arg3 = 214,
  OP_put_arg0 = 215,
  OP_put_arg1 = 216,
  OP_put_arg2 = 217,
  OP_put_arg3 = 218,
  OP_set_arg0 = 219,
  OP_set_arg1 = 220,
  OP_set_arg2 = 221,
  OP_set_arg3 = 222,
  OP_get_var_ref0 = 223,
  OP_get_var_ref1 = 224,
  OP_get_var_ref2 = 225,
  OP_get_var_ref3 = 226,
  OP_put_var_ref0 = 227,
  OP_put_var_ref1 = 228,
  OP_put_var_ref2 = 229,
  OP_put_var_ref3 = 230,
  OP_set_var_ref0 = 231,
  OP_set_var_ref1 = 232,
  OP_set_var_ref2 = 233,
  OP_set_var_ref3 = 234,
  OP_get_length = 235,
  OP_if_false8 = 236,
  OP_if_true8 = 237,
  OP_goto8 = 238,
  OP_goto16 = 239,
  OP_call0 = 240,
  OP_call1 = 241,
  OP_call2 = 242,
  OP_call3 = 243,
  OP_is_undefined = 244,
  OP_is_null = 245,
  OP_typeof_is_undefined = 246,
  OP_typeof_is_function = 247,
  OP_get_field_ic = 248,
  OP_get_field2_ic = 249,
  OP_put_field_ic = 250,
  OP_debugger = 251,
}

// 临时 opcodes: 只在编译阶段使用，ID 与 SHORT_OPCODES 重叠，最终字节码中不会出现
export enum TempOpcode {
  OP_enter_scope = 182,
  OP_leave_scope = 183,
  OP_label = 184,
  OP_scope_get_var_undef = 185,
  OP_scope_get_var = 186,
  OP_scope_put_var = 187,
  OP_scope_delete_var = 188,
  OP_scope_make_ref = 189,
  OP_scope_get_ref = 190,
  OP_scope_put_var_init = 191,
  OP_scope_get_var_checkthis = 192,
  OP_scope_get_private_field = 193,
  OP_scope_get_private_field2 = 194,
  OP_scope_put_private_field = 195,
  OP_scope_in_private_field = 196,
  OP_get_field_opt_chain = 197,
  OP_get_array_el_opt_chain = 198,
  OP_set_class_name = 199,
  OP_line_num = 200,
}

export const OPCODE_NAME_TO_CODE: Record<string, number> = {
  "invalid": 0,
  "push_i32": 1,
  "push_const": 2,
  "fclosure": 3,
  "push_atom_value": 4,
  "private_symbol": 5,
  "undefined": 6,
  "null": 7,
  "push_this": 8,
  "push_false": 9,
  "push_true": 10,
  "object": 11,
  "special_object": 12,
  "rest": 13,
  "drop": 14,
  "nip": 15,
  "nip1": 16,
  "dup": 17,
  "dup1": 18,
  "dup2": 19,
  "dup3": 20,
  "insert2": 21,
  "insert3": 22,
  "insert4": 23,
  "perm3": 24,
  "perm4": 25,
  "perm5": 26,
  "swap": 27,
  "swap2": 28,
  "rot3l": 29,
  "rot3r": 30,
  "rot4l": 31,
  "rot5l": 32,
  "call_constructor": 33,
  "call": 34,
  "tail_call": 35,
  "call_method": 36,
  "tail_call_method": 37,
  "array_from": 38,
  "apply": 39,
  "return": 40,
  "return_undef": 41,
  "check_ctor_return": 42,
  "check_ctor": 43,
  "init_ctor": 44,
  "check_brand": 45,
  "add_brand": 46,
  "return_async": 47,
  "throw": 48,
  "throw_error": 49,
  "eval": 50,
  "apply_eval": 51,
  "regexp": 52,
  "get_super": 53,
  "import": 54,
  "check_var": 55,
  "get_var_undef": 56,
  "get_var": 57,
  "put_var": 58,
  "put_var_init": 59,
  "put_var_strict": 60,
  "get_ref_value": 61,
  "put_ref_value": 62,
  "define_var": 63,
  "check_define_var": 64,
  "define_func": 65,
  "get_field": 66,
  "get_field2": 67,
  "put_field": 68,
  "get_private_field": 69,
  "put_private_field": 70,
  "define_private_field": 71,
  "get_array_el": 72,
  "get_array_el2": 73,
  "get_array_el3": 74,
  "put_array_el": 75,
  "get_super_value": 76,
  "put_super_value": 77,
  "define_field": 78,
  "set_name": 79,
  "set_name_computed": 80,
  "set_proto": 81,
  "set_home_object": 82,
  "define_array_el": 83,
  "append": 84,
  "copy_data_properties": 85,
  "define_method": 86,
  "define_method_computed": 87,
  "define_class": 88,
  "define_class_computed": 89,
  "get_loc": 90,
  "put_loc": 91,
  "set_loc": 92,
  "get_arg": 93,
  "put_arg": 94,
  "set_arg": 95,
  "get_var_ref": 96,
  "put_var_ref": 97,
  "set_var_ref": 98,
  "set_loc_uninitialized": 99,
  "get_loc_check": 100,
  "put_loc_check": 101,
  "put_loc_check_init": 102,
  "get_loc_checkthis": 103,
  "get_var_ref_check": 104,
  "put_var_ref_check": 105,
  "put_var_ref_check_init": 106,
  "close_loc": 107,
  "if_false": 108,
  "if_true": 109,
  "goto": 110,
  "catch": 111,
  "gosub": 112,
  "ret": 113,
  "nip_catch": 114,
  "to_object": 115,
  "to_propkey": 116,
  "with_get_var": 117,
  "with_put_var": 118,
  "with_delete_var": 119,
  "with_make_ref": 120,
  "with_get_ref": 121,
  "make_loc_ref": 122,
  "make_arg_ref": 123,
  "make_var_ref_ref": 124,
  "make_var_ref": 125,
  "for_in_start": 126,
  "for_of_start": 127,
  "for_await_of_start": 128,
  "for_in_next": 129,
  "for_of_next": 130,
  "for_await_of_next": 131,
  "iterator_check_object": 132,
  "iterator_get_value_done": 133,
  "iterator_close": 134,
  "iterator_next": 135,
  "iterator_call": 136,
  "initial_yield": 137,
  "yield": 138,
  "yield_star": 139,
  "async_yield_star": 140,
  "await": 141,
  "neg": 142,
  "plus": 143,
  "dec": 144,
  "inc": 145,
  "post_dec": 146,
  "post_inc": 147,
  "dec_loc": 148,
  "inc_loc": 149,
  "add_loc": 150,
  "not": 151,
  "lnot": 152,
  "typeof": 153,
  "delete": 154,
  "delete_var": 155,
  "mul": 156,
  "div": 157,
  "mod": 158,
  "add": 159,
  "sub": 160,
  "pow": 161,
  "shl": 162,
  "sar": 163,
  "shr": 164,
  "lt": 165,
  "lte": 166,
  "gt": 167,
  "gte": 168,
  "instanceof": 169,
  "in": 170,
  "eq": 171,
  "neq": 172,
  "strict_eq": 173,
  "strict_neq": 174,
  "and": 175,
  "xor": 176,
  "or": 177,
  "is_undefined_or_null": 178,
  "private_in": 179,
  "push_bigint_i32": 180,
  "nop": 181,
  "push_minus1": 182,
  "push_0": 183,
  "push_1": 184,
  "push_2": 185,
  "push_3": 186,
  "push_4": 187,
  "push_5": 188,
  "push_6": 189,
  "push_7": 190,
  "push_i8": 191,
  "push_i16": 192,
  "push_const8": 193,
  "fclosure8": 194,
  "push_empty_string": 195,
  "get_loc8": 196,
  "put_loc8": 197,
  "set_loc8": 198,
  "get_loc0": 199,
  "get_loc1": 200,
  "get_loc2": 201,
  "get_loc3": 202,
  "put_loc0": 203,
  "put_loc1": 204,
  "put_loc2": 205,
  "put_loc3": 206,
  "set_loc0": 207,
  "set_loc1": 208,
  "set_loc2": 209,
  "set_loc3": 210,
  "get_arg0": 211,
  "get_arg1": 212,
  "get_arg2": 213,
  "get_arg3": 214,
  "put_arg0": 215,
  "put_arg1": 216,
  "put_arg2": 217,
  "put_arg3": 218,
  "set_arg0": 219,
  "set_arg1": 220,
  "set_arg2": 221,
  "set_arg3": 222,
  "get_var_ref0": 223,
  "get_var_ref1": 224,
  "get_var_ref2": 225,
  "get_var_ref3": 226,
  "put_var_ref0": 227,
  "put_var_ref1": 228,
  "put_var_ref2": 229,
  "put_var_ref3": 230,
  "set_var_ref0": 231,
  "set_var_ref1": 232,
  "set_var_ref2": 233,
  "set_var_ref3": 234,
  "get_length": 235,
  "if_false8": 236,
  "if_true8": 237,
  "goto8": 238,
  "goto16": 239,
  "call0": 240,
  "call1": 241,
  "call2": 242,
  "call3": 243,
  "is_undefined": 244,
  "is_null": 245,
  "typeof_is_undefined": 246,
  "typeof_is_function": 247,
  "get_field_ic": 248,
  "get_field2_ic": 249,
  "put_field_ic": 250,
  "debugger": 251,
}

// 临时 opcodes: 只在编译阶段使用，ID 与 SHORT_OPCODES 重叠
export const TEMP_OPCODE_NAME_TO_CODE: Record<string, number> = {
  "enter_scope": 182,
  "leave_scope": 183,
  "label": 184,
  "scope_get_var_undef": 185,
  "scope_get_var": 186,
  "scope_put_var": 187,
  "scope_delete_var": 188,
  "scope_make_ref": 189,
  "scope_get_ref": 190,
  "scope_put_var_init": 191,
  "scope_get_var_checkthis": 192,
  "scope_get_private_field": 193,
  "scope_get_private_field2": 194,
  "scope_put_private_field": 195,
  "scope_in_private_field": 196,
  "get_field_opt_chain": 197,
  "get_array_el_opt_chain": 198,
  "set_class_name": 199,
  "line_num": 200,
}

export enum JSAtom {
  JS_ATOM_null = 1,
  JS_ATOM_false = 2,
  JS_ATOM_true = 3,
  JS_ATOM_if = 4,
  JS_ATOM_else = 5,
  JS_ATOM_return = 6,
  JS_ATOM_var = 7,
  JS_ATOM_this = 8,
  JS_ATOM_delete = 9,
  JS_ATOM_void = 10,
  JS_ATOM_typeof = 11,
  JS_ATOM_new = 12,
  JS_ATOM_in = 13,
  JS_ATOM_instanceof = 14,
  JS_ATOM_do = 15,
  JS_ATOM_while = 16,
  JS_ATOM_for = 17,
  JS_ATOM_break = 18,
  JS_ATOM_continue = 19,
  JS_ATOM_switch = 20,
  JS_ATOM_case = 21,
  JS_ATOM_default = 22,
  JS_ATOM_throw = 23,
  JS_ATOM_try = 24,
  JS_ATOM_catch = 25,
  JS_ATOM_finally = 26,
  JS_ATOM_function = 27,
  JS_ATOM_debugger = 28,
  JS_ATOM_with = 29,
  JS_ATOM_class = 30,
  JS_ATOM_const = 31,
  JS_ATOM_enum = 32,
  JS_ATOM_export = 33,
  JS_ATOM_extends = 34,
  JS_ATOM_import = 35,
  JS_ATOM_super = 36,
  JS_ATOM_implements = 37,
  JS_ATOM_interface = 38,
  JS_ATOM_let = 39,
  JS_ATOM_package = 40,
  JS_ATOM_private = 41,
  JS_ATOM_protected = 42,
  JS_ATOM_public = 43,
  JS_ATOM_static = 44,
  JS_ATOM_yield = 45,
  JS_ATOM_await = 46,
  JS_ATOM_empty_string = 47,
  JS_ATOM_length = 48,
  JS_ATOM_fileName = 49,
  JS_ATOM_lineNumber = 50,
  JS_ATOM_columnNumber = 51,
  JS_ATOM_message = 52,
  JS_ATOM_cause = 53,
  JS_ATOM_errors = 54,
  JS_ATOM_stack = 55,
  JS_ATOM_name = 56,
  JS_ATOM_toString = 57,
  JS_ATOM_toLocaleString = 58,
  JS_ATOM_valueOf = 59,
  JS_ATOM_eval = 60,
  JS_ATOM_prototype = 61,
  JS_ATOM_constructor = 62,
  JS_ATOM_configurable = 63,
  JS_ATOM_writable = 64,
  JS_ATOM_enumerable = 65,
  JS_ATOM_value = 66,
  JS_ATOM_get = 67,
  JS_ATOM_set = 68,
  JS_ATOM_of = 69,
  JS_ATOM___proto__ = 70,
  JS_ATOM_undefined = 71,
  JS_ATOM_number = 72,
  JS_ATOM_boolean = 73,
  JS_ATOM_string = 74,
  JS_ATOM_object = 75,
  JS_ATOM_symbol = 76,
  JS_ATOM_integer = 77,
  JS_ATOM_unknown = 78,
  JS_ATOM_arguments = 79,
  JS_ATOM_callee = 80,
  JS_ATOM_caller = 81,
  JS_ATOM__eval_ = 82,
  JS_ATOM__ret_ = 83,
  JS_ATOM__var_ = 84,
  JS_ATOM__arg_var_ = 85,
  JS_ATOM__with_ = 86,
  JS_ATOM_lastIndex = 87,
  JS_ATOM_target = 88,
  JS_ATOM_index = 89,
  JS_ATOM_input = 90,
  JS_ATOM_defineProperties = 91,
  JS_ATOM_apply = 92,
  JS_ATOM_join = 93,
  JS_ATOM_concat = 94,
  JS_ATOM_split = 95,
  JS_ATOM_construct = 96,
  JS_ATOM_getPrototypeOf = 97,
  JS_ATOM_setPrototypeOf = 98,
  JS_ATOM_isExtensible = 99,
  JS_ATOM_preventExtensions = 100,
  JS_ATOM_has = 101,
  JS_ATOM_deleteProperty = 102,
  JS_ATOM_defineProperty = 103,
  JS_ATOM_getOwnPropertyDescriptor = 104,
  JS_ATOM_ownKeys = 105,
  JS_ATOM_add = 106,
  JS_ATOM_done = 107,
  JS_ATOM_next = 108,
  JS_ATOM_values = 109,
  JS_ATOM_source = 110,
  JS_ATOM_flags = 111,
  JS_ATOM_global = 112,
  JS_ATOM_unicode = 113,
  JS_ATOM_raw = 114,
  JS_ATOM_new_target = 115,
  JS_ATOM_this_active_func = 116,
  JS_ATOM_home_object = 117,
  JS_ATOM_computed_field = 118,
  JS_ATOM_static_computed_field = 119,
  JS_ATOM_class_fields_init = 120,
  JS_ATOM_brand = 121,
  JS_ATOM_hash_constructor = 122,
  JS_ATOM_as = 123,
  JS_ATOM_from = 124,
  JS_ATOM_meta = 125,
  JS_ATOM__default_ = 126,
  JS_ATOM__star_ = 127,
  JS_ATOM_Module = 128,
  JS_ATOM_then = 129,
  JS_ATOM_resolve = 130,
  JS_ATOM_reject = 131,
  JS_ATOM_promise = 132,
  JS_ATOM_proxy = 133,
  JS_ATOM_revoke = 134,
  JS_ATOM_async = 135,
  JS_ATOM_exec = 136,
  JS_ATOM_groups = 137,
  JS_ATOM_indices = 138,
  JS_ATOM_status = 139,
  JS_ATOM_reason = 140,
  JS_ATOM_globalThis = 141,
  JS_ATOM_bigint = 142,
  JS_ATOM_minus_zero = 143,
  JS_ATOM_Infinity = 144,
  JS_ATOM_minus_Infinity = 145,
  JS_ATOM_NaN = 146,
  JS_ATOM_hasIndices = 147,
  JS_ATOM_ignoreCase = 148,
  JS_ATOM_multiline = 149,
  JS_ATOM_dotAll = 150,
  JS_ATOM_sticky = 151,
  JS_ATOM_unicodeSets = 152,
  JS_ATOM_not_equal = 153,
  JS_ATOM_timed_out = 154,
  JS_ATOM_ok = 155,
  JS_ATOM_toJSON = 156,
  JS_ATOM_Object = 157,
  JS_ATOM_Array = 158,
  JS_ATOM_Error = 159,
  JS_ATOM_Number = 160,
  JS_ATOM_String = 161,
  JS_ATOM_Boolean = 162,
  JS_ATOM_Symbol = 163,
  JS_ATOM_Arguments = 164,
  JS_ATOM_Math = 165,
  JS_ATOM_JSON = 166,
  JS_ATOM_Date = 167,
  JS_ATOM_Function = 168,
  JS_ATOM_GeneratorFunction = 169,
  JS_ATOM_ForInIterator = 170,
  JS_ATOM_RegExp = 171,
  JS_ATOM_ArrayBuffer = 172,
  JS_ATOM_SharedArrayBuffer = 173,
  JS_ATOM_Uint8ClampedArray = 174,
  JS_ATOM_Int8Array = 175,
  JS_ATOM_Uint8Array = 176,
  JS_ATOM_Int16Array = 177,
  JS_ATOM_Uint16Array = 178,
  JS_ATOM_Int32Array = 179,
  JS_ATOM_Uint32Array = 180,
  JS_ATOM_Float16Array = 181,
  JS_ATOM_Float32Array = 182,
  JS_ATOM_Float64Array = 183,
  JS_ATOM_DataView = 184,
  JS_ATOM_BigInt = 185,
  JS_ATOM_WeakRef = 186,
  JS_ATOM_FinalizationRegistry = 187,
  JS_ATOM_Map = 188,
  JS_ATOM_Set = 189,
  JS_ATOM_WeakMap = 190,
  JS_ATOM_WeakSet = 191,
  JS_ATOM_Map_Iterator = 192,
  JS_ATOM_Set_Iterator = 193,
  JS_ATOM_Array_Iterator = 194,
  JS_ATOM_String_Iterator = 195,
  JS_ATOM_RegExp_String_Iterator = 196,
  JS_ATOM_Generator = 197,
  JS_ATOM_Proxy = 198,
  JS_ATOM_Promise = 199,
  JS_ATOM_PromiseResolveFunction = 200,
  JS_ATOM_PromiseRejectFunction = 201,
  JS_ATOM_AsyncFunction = 202,
  JS_ATOM_AsyncFunctionResolve = 203,
  JS_ATOM_AsyncFunctionReject = 204,
  JS_ATOM_AsyncGeneratorFunction = 205,
  JS_ATOM_AsyncGenerator = 206,
  JS_ATOM_EvalError = 207,
  JS_ATOM_RangeError = 208,
  JS_ATOM_ReferenceError = 209,
  JS_ATOM_SyntaxError = 210,
  JS_ATOM_TypeError = 211,
  JS_ATOM_URIError = 212,
  JS_ATOM_InternalError = 213,
  JS_ATOM_Private_brand = 214,
  JS_ATOM_Symbol_toPrimitive = 215,
  JS_ATOM_Symbol_iterator = 216,
  JS_ATOM_Symbol_match = 217,
  JS_ATOM_Symbol_matchAll = 218,
  JS_ATOM_Symbol_replace = 219,
  JS_ATOM_Symbol_search = 220,
  JS_ATOM_Symbol_split = 221,
  JS_ATOM_Symbol_toStringTag = 222,
  JS_ATOM_Symbol_isConcatSpreadable = 223,
  JS_ATOM_Symbol_hasInstance = 224,
  JS_ATOM_Symbol_species = 225,
  JS_ATOM_Symbol_unscopables = 226,
  JS_ATOM_Symbol_asyncIterator = 227,
}

export const ATOM_STRINGS: Record<number, string> = {
  1: "null",
  2: "false",
  3: "true",
  4: "if",
  5: "else",
  6: "return",
  7: "var",
  8: "this",
  9: "delete",
  10: "void",
  11: "typeof",
  12: "new",
  13: "in",
  14: "instanceof",
  15: "do",
  16: "while",
  17: "for",
  18: "break",
  19: "continue",
  20: "switch",
  21: "case",
  22: "default",
  23: "throw",
  24: "try",
  25: "catch",
  26: "finally",
  27: "function",
  28: "debugger",
  29: "with",
  30: "class",
  31: "const",
  32: "enum",
  33: "export",
  34: "extends",
  35: "import",
  36: "super",
  37: "implements",
  38: "interface",
  39: "let",
  40: "package",
  41: "private",
  42: "protected",
  43: "public",
  44: "static",
  45: "yield",
  46: "await",
  47: "",
  48: "length",
  49: "fileName",
  50: "lineNumber",
  51: "columnNumber",
  52: "message",
  53: "cause",
  54: "errors",
  55: "stack",
  56: "name",
  57: "toString",
  58: "toLocaleString",
  59: "valueOf",
  60: "eval",
  61: "prototype",
  62: "constructor",
  63: "configurable",
  64: "writable",
  65: "enumerable",
  66: "value",
  67: "get",
  68: "set",
  69: "of",
  70: "__proto__",
  71: "undefined",
  72: "number",
  73: "boolean",
  74: "string",
  75: "object",
  76: "symbol",
  77: "integer",
  78: "unknown",
  79: "arguments",
  80: "callee",
  81: "caller",
  82: "<eval>",
  83: "<ret>",
  84: "<var>",
  85: "<arg_var>",
  86: "<with>",
  87: "lastIndex",
  88: "target",
  89: "index",
  90: "input",
  91: "defineProperties",
  92: "apply",
  93: "join",
  94: "concat",
  95: "split",
  96: "construct",
  97: "getPrototypeOf",
  98: "setPrototypeOf",
  99: "isExtensible",
  100: "preventExtensions",
  101: "has",
  102: "deleteProperty",
  103: "defineProperty",
  104: "getOwnPropertyDescriptor",
  105: "ownKeys",
  106: "add",
  107: "done",
  108: "next",
  109: "values",
  110: "source",
  111: "flags",
  112: "global",
  113: "unicode",
  114: "raw",
  115: "new.target",
  116: "this.active_func",
  117: "<home_object>",
  118: "<computed_field>",
  119: "<static_computed_field>",
  120: "<class_fields_init>",
  121: "<brand>",
  122: "#constructor",
  123: "as",
  124: "from",
  125: "meta",
  126: "*default*",
  127: "*",
  128: "Module",
  129: "then",
  130: "resolve",
  131: "reject",
  132: "promise",
  133: "proxy",
  134: "revoke",
  135: "async",
  136: "exec",
  137: "groups",
  138: "indices",
  139: "status",
  140: "reason",
  141: "globalThis",
  142: "bigint",
  143: "-0",
  144: "Infinity",
  145: "-Infinity",
  146: "NaN",
  147: "hasIndices",
  148: "ignoreCase",
  149: "multiline",
  150: "dotAll",
  151: "sticky",
  152: "unicodeSets",
  153: "not-equal",
  154: "timed-out",
  155: "ok",
  156: "toJSON",
  157: "Object",
  158: "Array",
  159: "Error",
  160: "Number",
  161: "String",
  162: "Boolean",
  163: "Symbol",
  164: "Arguments",
  165: "Math",
  166: "JSON",
  167: "Date",
  168: "Function",
  169: "GeneratorFunction",
  170: "ForInIterator",
  171: "RegExp",
  172: "ArrayBuffer",
  173: "SharedArrayBuffer",
  174: "Uint8ClampedArray",
  175: "Int8Array",
  176: "Uint8Array",
  177: "Int16Array",
  178: "Uint16Array",
  179: "Int32Array",
  180: "Uint32Array",
  181: "Float16Array",
  182: "Float32Array",
  183: "Float64Array",
  184: "DataView",
  185: "BigInt",
  186: "WeakRef",
  187: "FinalizationRegistry",
  188: "Map",
  189: "Set",
  190: "WeakMap",
  191: "WeakSet",
  192: "Map Iterator",
  193: "Set Iterator",
  194: "Array Iterator",
  195: "String Iterator",
  196: "RegExp String Iterator",
  197: "Generator",
  198: "Proxy",
  199: "Promise",
  200: "PromiseResolveFunction",
  201: "PromiseRejectFunction",
  202: "AsyncFunction",
  203: "AsyncFunctionResolve",
  204: "AsyncFunctionReject",
  205: "AsyncGeneratorFunction",
  206: "AsyncGenerator",
  207: "EvalError",
  208: "RangeError",
  209: "ReferenceError",
  210: "SyntaxError",
  211: "TypeError",
  212: "URIError",
  213: "InternalError",
  214: "<brand>",
  215: "Symbol.toPrimitive",
  216: "Symbol.iterator",
  217: "Symbol.match",
  218: "Symbol.matchAll",
  219: "Symbol.replace",
  220: "Symbol.search",
  221: "Symbol.split",
  222: "Symbol.toStringTag",
  223: "Symbol.isConcatSpreadable",
  224: "Symbol.hasInstance",
  225: "Symbol.species",
  226: "Symbol.unscopables",
  227: "Symbol.asyncIterator",
}

export interface OpcodeDefinition {
  id: string
  size: number
  nPop: number
  nPush: number
  format: OpFormat
}

export const OPCODE_DEFS: Record<string, OpcodeDefinition> = {
  OP_invalid: { id: "invalid", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
  OP_push_i32: { id: "push_i32", size: 5, nPop: 0, nPush: 1, format: OpFormat.i32 },
  OP_push_const: { id: "push_const", size: 5, nPop: 0, nPush: 1, format: OpFormat.const },
  OP_fclosure: { id: "fclosure", size: 5, nPop: 0, nPush: 1, format: OpFormat.const },
  OP_push_atom_value: { id: "push_atom_value", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  OP_private_symbol: { id: "private_symbol", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  OP_undefined: { id: "undefined", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_null: { id: "null", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_push_this: { id: "push_this", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_push_false: { id: "push_false", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_push_true: { id: "push_true", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_object: { id: "object", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_special_object: { id: "special_object", size: 2, nPop: 0, nPush: 1, format: OpFormat.u8 },
  OP_rest: { id: "rest", size: 3, nPop: 0, nPush: 1, format: OpFormat.u16 },
  OP_drop: { id: "drop", size: 1, nPop: 1, nPush: 0, format: OpFormat.none },
  OP_nip: { id: "nip", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_nip1: { id: "nip1", size: 1, nPop: 3, nPush: 2, format: OpFormat.none },
  OP_dup: { id: "dup", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_dup1: { id: "dup1", size: 1, nPop: 2, nPush: 3, format: OpFormat.none },
  OP_dup2: { id: "dup2", size: 1, nPop: 2, nPush: 4, format: OpFormat.none },
  OP_dup3: { id: "dup3", size: 1, nPop: 3, nPush: 6, format: OpFormat.none },
  OP_insert2: { id: "insert2", size: 1, nPop: 2, nPush: 3, format: OpFormat.none },
  OP_insert3: { id: "insert3", size: 1, nPop: 3, nPush: 4, format: OpFormat.none },
  OP_insert4: { id: "insert4", size: 1, nPop: 4, nPush: 5, format: OpFormat.none },
  OP_perm3: { id: "perm3", size: 1, nPop: 3, nPush: 3, format: OpFormat.none },
  OP_perm4: { id: "perm4", size: 1, nPop: 4, nPush: 4, format: OpFormat.none },
  OP_perm5: { id: "perm5", size: 1, nPop: 5, nPush: 5, format: OpFormat.none },
  OP_swap: { id: "swap", size: 1, nPop: 2, nPush: 2, format: OpFormat.none },
  OP_swap2: { id: "swap2", size: 1, nPop: 4, nPush: 4, format: OpFormat.none },
  OP_rot3l: { id: "rot3l", size: 1, nPop: 3, nPush: 3, format: OpFormat.none },
  OP_rot3r: { id: "rot3r", size: 1, nPop: 3, nPush: 3, format: OpFormat.none },
  OP_rot4l: { id: "rot4l", size: 1, nPop: 4, nPush: 4, format: OpFormat.none },
  OP_rot5l: { id: "rot5l", size: 1, nPop: 5, nPush: 5, format: OpFormat.none },
  OP_call_constructor: { id: "call_constructor", size: 3, nPop: 2, nPush: 1, format: OpFormat.npop },
  OP_call: { id: "call", size: 3, nPop: 1, nPush: 1, format: OpFormat.npop },
  OP_tail_call: { id: "tail_call", size: 3, nPop: 1, nPush: 0, format: OpFormat.npop },
  OP_call_method: { id: "call_method", size: 3, nPop: 2, nPush: 1, format: OpFormat.npop },
  OP_tail_call_method: { id: "tail_call_method", size: 3, nPop: 2, nPush: 0, format: OpFormat.npop },
  OP_array_from: { id: "array_from", size: 3, nPop: 0, nPush: 1, format: OpFormat.npop },
  OP_apply: { id: "apply", size: 3, nPop: 3, nPush: 1, format: OpFormat.u16 },
  OP_return: { id: "return", size: 1, nPop: 1, nPush: 0, format: OpFormat.none },
  OP_return_undef: { id: "return_undef", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
  OP_check_ctor_return: { id: "check_ctor_return", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_check_ctor: { id: "check_ctor", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
  OP_init_ctor: { id: "init_ctor", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_check_brand: { id: "check_brand", size: 1, nPop: 2, nPush: 2, format: OpFormat.none },
  OP_add_brand: { id: "add_brand", size: 1, nPop: 2, nPush: 0, format: OpFormat.none },
  OP_return_async: { id: "return_async", size: 1, nPop: 1, nPush: 0, format: OpFormat.none },
  OP_throw: { id: "throw", size: 1, nPop: 1, nPush: 0, format: OpFormat.none },
  OP_throw_error: { id: "throw_error", size: 6, nPop: 0, nPush: 0, format: OpFormat.atom_u8 },
  OP_eval: { id: "eval", size: 5, nPop: 1, nPush: 1, format: OpFormat.npop_u16 },
  OP_apply_eval: { id: "apply_eval", size: 3, nPop: 2, nPush: 1, format: OpFormat.u16 },
  OP_regexp: { id: "regexp", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_get_super: { id: "get_super", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_import: { id: "import", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_check_var: { id: "check_var", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  OP_get_var_undef: { id: "get_var_undef", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  OP_get_var: { id: "get_var", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  OP_put_var: { id: "put_var", size: 5, nPop: 1, nPush: 0, format: OpFormat.atom },
  OP_put_var_init: { id: "put_var_init", size: 5, nPop: 1, nPush: 0, format: OpFormat.atom },
  OP_put_var_strict: { id: "put_var_strict", size: 5, nPop: 2, nPush: 0, format: OpFormat.atom },
  OP_get_ref_value: { id: "get_ref_value", size: 1, nPop: 2, nPush: 3, format: OpFormat.none },
  OP_put_ref_value: { id: "put_ref_value", size: 1, nPop: 3, nPush: 0, format: OpFormat.none },
  OP_define_var: { id: "define_var", size: 6, nPop: 0, nPush: 0, format: OpFormat.atom_u8 },
  OP_check_define_var: { id: "check_define_var", size: 6, nPop: 0, nPush: 0, format: OpFormat.atom_u8 },
  OP_define_func: { id: "define_func", size: 6, nPop: 1, nPush: 0, format: OpFormat.atom_u8 },
  OP_get_field: { id: "get_field", size: 5, nPop: 1, nPush: 1, format: OpFormat.atom },
  OP_get_field2: { id: "get_field2", size: 5, nPop: 1, nPush: 2, format: OpFormat.atom },
  OP_put_field: { id: "put_field", size: 5, nPop: 2, nPush: 0, format: OpFormat.atom },
  OP_get_private_field: { id: "get_private_field", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_put_private_field: { id: "put_private_field", size: 1, nPop: 3, nPush: 0, format: OpFormat.none },
  OP_define_private_field: { id: "define_private_field", size: 1, nPop: 3, nPush: 1, format: OpFormat.none },
  OP_get_array_el: { id: "get_array_el", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_get_array_el2: { id: "get_array_el2", size: 1, nPop: 2, nPush: 2, format: OpFormat.none },
  OP_get_array_el3: { id: "get_array_el3", size: 1, nPop: 2, nPush: 3, format: OpFormat.none },
  OP_put_array_el: { id: "put_array_el", size: 1, nPop: 3, nPush: 0, format: OpFormat.none },
  OP_get_super_value: { id: "get_super_value", size: 1, nPop: 3, nPush: 1, format: OpFormat.none },
  OP_put_super_value: { id: "put_super_value", size: 1, nPop: 4, nPush: 0, format: OpFormat.none },
  OP_define_field: { id: "define_field", size: 5, nPop: 2, nPush: 1, format: OpFormat.atom },
  OP_set_name: { id: "set_name", size: 5, nPop: 1, nPush: 1, format: OpFormat.atom },
  OP_set_name_computed: { id: "set_name_computed", size: 1, nPop: 2, nPush: 2, format: OpFormat.none },
  OP_set_proto: { id: "set_proto", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_set_home_object: { id: "set_home_object", size: 1, nPop: 2, nPush: 2, format: OpFormat.none },
  OP_define_array_el: { id: "define_array_el", size: 1, nPop: 3, nPush: 2, format: OpFormat.none },
  OP_append: { id: "append", size: 1, nPop: 3, nPush: 2, format: OpFormat.none },
  OP_copy_data_properties: { id: "copy_data_properties", size: 2, nPop: 3, nPush: 3, format: OpFormat.u8 },
  OP_define_method: { id: "define_method", size: 6, nPop: 2, nPush: 1, format: OpFormat.atom_u8 },
  OP_define_method_computed: { id: "define_method_computed", size: 2, nPop: 3, nPush: 1, format: OpFormat.u8 },
  OP_define_class: { id: "define_class", size: 6, nPop: 2, nPush: 2, format: OpFormat.atom_u8 },
  OP_define_class_computed: { id: "define_class_computed", size: 6, nPop: 3, nPush: 3, format: OpFormat.atom_u8 },
  OP_get_loc: { id: "get_loc", size: 3, nPop: 0, nPush: 1, format: OpFormat.loc },
  OP_put_loc: { id: "put_loc", size: 3, nPop: 1, nPush: 0, format: OpFormat.loc },
  OP_set_loc: { id: "set_loc", size: 3, nPop: 1, nPush: 1, format: OpFormat.loc },
  OP_get_arg: { id: "get_arg", size: 3, nPop: 0, nPush: 1, format: OpFormat.arg },
  OP_put_arg: { id: "put_arg", size: 3, nPop: 1, nPush: 0, format: OpFormat.arg },
  OP_set_arg: { id: "set_arg", size: 3, nPop: 1, nPush: 1, format: OpFormat.arg },
  OP_get_var_ref: { id: "get_var_ref", size: 3, nPop: 0, nPush: 1, format: OpFormat.var_ref },
  OP_put_var_ref: { id: "put_var_ref", size: 3, nPop: 1, nPush: 0, format: OpFormat.var_ref },
  OP_set_var_ref: { id: "set_var_ref", size: 3, nPop: 1, nPush: 1, format: OpFormat.var_ref },
  OP_set_loc_uninitialized: { id: "set_loc_uninitialized", size: 3, nPop: 0, nPush: 0, format: OpFormat.loc },
  OP_get_loc_check: { id: "get_loc_check", size: 3, nPop: 0, nPush: 1, format: OpFormat.loc },
  OP_put_loc_check: { id: "put_loc_check", size: 3, nPop: 1, nPush: 0, format: OpFormat.loc },
  OP_put_loc_check_init: { id: "put_loc_check_init", size: 3, nPop: 1, nPush: 0, format: OpFormat.loc },
  OP_get_loc_checkthis: { id: "get_loc_checkthis", size: 3, nPop: 0, nPush: 1, format: OpFormat.loc },
  OP_get_var_ref_check: { id: "get_var_ref_check", size: 3, nPop: 0, nPush: 1, format: OpFormat.var_ref },
  OP_put_var_ref_check: { id: "put_var_ref_check", size: 3, nPop: 1, nPush: 0, format: OpFormat.var_ref },
  OP_put_var_ref_check_init: { id: "put_var_ref_check_init", size: 3, nPop: 1, nPush: 0, format: OpFormat.var_ref },
  OP_close_loc: { id: "close_loc", size: 3, nPop: 0, nPush: 0, format: OpFormat.loc },
  OP_if_false: { id: "if_false", size: 5, nPop: 1, nPush: 0, format: OpFormat.label },
  OP_if_true: { id: "if_true", size: 5, nPop: 1, nPush: 0, format: OpFormat.label },
  OP_goto: { id: "goto", size: 5, nPop: 0, nPush: 0, format: OpFormat.label },
  OP_catch: { id: "catch", size: 5, nPop: 0, nPush: 1, format: OpFormat.label },
  OP_gosub: { id: "gosub", size: 5, nPop: 0, nPush: 0, format: OpFormat.label },
  OP_ret: { id: "ret", size: 1, nPop: 1, nPush: 0, format: OpFormat.none },
  OP_nip_catch: { id: "nip_catch", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_to_object: { id: "to_object", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_to_propkey: { id: "to_propkey", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_with_get_var: { id: "with_get_var", size: 10, nPop: 1, nPush: 0, format: OpFormat.atom_label_u8 },
  OP_with_put_var: { id: "with_put_var", size: 10, nPop: 2, nPush: 1, format: OpFormat.atom_label_u8 },
  OP_with_delete_var: { id: "with_delete_var", size: 10, nPop: 1, nPush: 0, format: OpFormat.atom_label_u8 },
  OP_with_make_ref: { id: "with_make_ref", size: 10, nPop: 1, nPush: 0, format: OpFormat.atom_label_u8 },
  OP_with_get_ref: { id: "with_get_ref", size: 10, nPop: 1, nPush: 0, format: OpFormat.atom_label_u8 },
  OP_make_loc_ref: { id: "make_loc_ref", size: 7, nPop: 0, nPush: 2, format: OpFormat.atom_u16 },
  OP_make_arg_ref: { id: "make_arg_ref", size: 7, nPop: 0, nPush: 2, format: OpFormat.atom_u16 },
  OP_make_var_ref_ref: { id: "make_var_ref_ref", size: 7, nPop: 0, nPush: 2, format: OpFormat.atom_u16 },
  OP_make_var_ref: { id: "make_var_ref", size: 5, nPop: 0, nPush: 2, format: OpFormat.atom },
  OP_for_in_start: { id: "for_in_start", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_for_of_start: { id: "for_of_start", size: 1, nPop: 1, nPush: 3, format: OpFormat.none },
  OP_for_await_of_start: { id: "for_await_of_start", size: 1, nPop: 1, nPush: 3, format: OpFormat.none },
  OP_for_in_next: { id: "for_in_next", size: 1, nPop: 1, nPush: 3, format: OpFormat.none },
  OP_for_of_next: { id: "for_of_next", size: 2, nPop: 3, nPush: 5, format: OpFormat.u8 },
  OP_for_await_of_next: { id: "for_await_of_next", size: 1, nPop: 3, nPush: 4, format: OpFormat.none },
  OP_iterator_check_object: { id: "iterator_check_object", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_iterator_get_value_done: { id: "iterator_get_value_done", size: 1, nPop: 2, nPush: 3, format: OpFormat.none },
  OP_iterator_close: { id: "iterator_close", size: 1, nPop: 3, nPush: 0, format: OpFormat.none },
  OP_iterator_next: { id: "iterator_next", size: 1, nPop: 4, nPush: 4, format: OpFormat.none },
  OP_iterator_call: { id: "iterator_call", size: 2, nPop: 4, nPush: 5, format: OpFormat.u8 },
  OP_initial_yield: { id: "initial_yield", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
  OP_yield: { id: "yield", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_yield_star: { id: "yield_star", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_async_yield_star: { id: "async_yield_star", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_await: { id: "await", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_neg: { id: "neg", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_plus: { id: "plus", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_dec: { id: "dec", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_inc: { id: "inc", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_post_dec: { id: "post_dec", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_post_inc: { id: "post_inc", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_dec_loc: { id: "dec_loc", size: 2, nPop: 0, nPush: 0, format: OpFormat.loc8 },
  OP_inc_loc: { id: "inc_loc", size: 2, nPop: 0, nPush: 0, format: OpFormat.loc8 },
  OP_add_loc: { id: "add_loc", size: 2, nPop: 1, nPush: 0, format: OpFormat.loc8 },
  OP_not: { id: "not", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_lnot: { id: "lnot", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_typeof: { id: "typeof", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_delete: { id: "delete", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_delete_var: { id: "delete_var", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  OP_mul: { id: "mul", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_div: { id: "div", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_mod: { id: "mod", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_add: { id: "add", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_sub: { id: "sub", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_pow: { id: "pow", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_shl: { id: "shl", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_sar: { id: "sar", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_shr: { id: "shr", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_lt: { id: "lt", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_lte: { id: "lte", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_gt: { id: "gt", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_gte: { id: "gte", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_instanceof: { id: "instanceof", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_in: { id: "in", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_eq: { id: "eq", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_neq: { id: "neq", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_strict_eq: { id: "strict_eq", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_strict_neq: { id: "strict_neq", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_and: { id: "and", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_xor: { id: "xor", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_or: { id: "or", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_is_undefined_or_null: { id: "is_undefined_or_null", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_private_in: { id: "private_in", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_push_bigint_i32: { id: "push_bigint_i32", size: 5, nPop: 0, nPush: 1, format: OpFormat.i32 },
  OP_nop: { id: "nop", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
  OP_push_minus1: { id: "push_minus1", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_0: { id: "push_0", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_1: { id: "push_1", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_2: { id: "push_2", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_3: { id: "push_3", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_4: { id: "push_4", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_5: { id: "push_5", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_6: { id: "push_6", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_7: { id: "push_7", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_i8: { id: "push_i8", size: 2, nPop: 0, nPush: 1, format: OpFormat.i8 },
  OP_push_i16: { id: "push_i16", size: 3, nPop: 0, nPush: 1, format: OpFormat.i16 },
  OP_push_const8: { id: "push_const8", size: 2, nPop: 0, nPush: 1, format: OpFormat.const8 },
  OP_fclosure8: { id: "fclosure8", size: 2, nPop: 0, nPush: 1, format: OpFormat.const8 },
  OP_push_empty_string: { id: "push_empty_string", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_get_loc8: { id: "get_loc8", size: 2, nPop: 0, nPush: 1, format: OpFormat.loc8 },
  OP_put_loc8: { id: "put_loc8", size: 2, nPop: 1, nPush: 0, format: OpFormat.loc8 },
  OP_set_loc8: { id: "set_loc8", size: 2, nPop: 1, nPush: 1, format: OpFormat.loc8 },
  OP_get_loc0: { id: "get_loc0", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_loc },
  OP_get_loc1: { id: "get_loc1", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_loc },
  OP_get_loc2: { id: "get_loc2", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_loc },
  OP_get_loc3: { id: "get_loc3", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_loc },
  OP_put_loc0: { id: "put_loc0", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_loc },
  OP_put_loc1: { id: "put_loc1", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_loc },
  OP_put_loc2: { id: "put_loc2", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_loc },
  OP_put_loc3: { id: "put_loc3", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_loc },
  OP_set_loc0: { id: "set_loc0", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_loc },
  OP_set_loc1: { id: "set_loc1", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_loc },
  OP_set_loc2: { id: "set_loc2", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_loc },
  OP_set_loc3: { id: "set_loc3", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_loc },
  OP_get_arg0: { id: "get_arg0", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_arg },
  OP_get_arg1: { id: "get_arg1", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_arg },
  OP_get_arg2: { id: "get_arg2", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_arg },
  OP_get_arg3: { id: "get_arg3", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_arg },
  OP_put_arg0: { id: "put_arg0", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_arg },
  OP_put_arg1: { id: "put_arg1", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_arg },
  OP_put_arg2: { id: "put_arg2", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_arg },
  OP_put_arg3: { id: "put_arg3", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_arg },
  OP_set_arg0: { id: "set_arg0", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_arg },
  OP_set_arg1: { id: "set_arg1", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_arg },
  OP_set_arg2: { id: "set_arg2", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_arg },
  OP_set_arg3: { id: "set_arg3", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_arg },
  OP_get_var_ref0: { id: "get_var_ref0", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_var_ref },
  OP_get_var_ref1: { id: "get_var_ref1", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_var_ref },
  OP_get_var_ref2: { id: "get_var_ref2", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_var_ref },
  OP_get_var_ref3: { id: "get_var_ref3", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_var_ref },
  OP_put_var_ref0: { id: "put_var_ref0", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_var_ref },
  OP_put_var_ref1: { id: "put_var_ref1", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_var_ref },
  OP_put_var_ref2: { id: "put_var_ref2", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_var_ref },
  OP_put_var_ref3: { id: "put_var_ref3", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_var_ref },
  OP_set_var_ref0: { id: "set_var_ref0", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_var_ref },
  OP_set_var_ref1: { id: "set_var_ref1", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_var_ref },
  OP_set_var_ref2: { id: "set_var_ref2", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_var_ref },
  OP_set_var_ref3: { id: "set_var_ref3", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_var_ref },
  OP_get_length: { id: "get_length", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_if_false8: { id: "if_false8", size: 2, nPop: 1, nPush: 0, format: OpFormat.label8 },
  OP_if_true8: { id: "if_true8", size: 2, nPop: 1, nPush: 0, format: OpFormat.label8 },
  OP_goto8: { id: "goto8", size: 2, nPop: 0, nPush: 0, format: OpFormat.label8 },
  OP_goto16: { id: "goto16", size: 3, nPop: 0, nPush: 0, format: OpFormat.label16 },
  OP_call0: { id: "call0", size: 1, nPop: 1, nPush: 1, format: OpFormat.npopx },
  OP_call1: { id: "call1", size: 1, nPop: 1, nPush: 1, format: OpFormat.npopx },
  OP_call2: { id: "call2", size: 1, nPop: 1, nPush: 1, format: OpFormat.npopx },
  OP_call3: { id: "call3", size: 1, nPop: 1, nPush: 1, format: OpFormat.npopx },
  OP_is_undefined: { id: "is_undefined", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_is_null: { id: "is_null", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_typeof_is_undefined: { id: "typeof_is_undefined", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_typeof_is_function: { id: "typeof_is_function", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_get_field_ic: { id: "get_field_ic", size: 5, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_get_field2_ic: { id: "get_field2_ic", size: 5, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_put_field_ic: { id: "put_field_ic", size: 5, nPop: 2, nPush: 0, format: OpFormat.none },
  OP_debugger: { id: "debugger", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
}

export const OPCODE_BY_CODE: Record<number, OpcodeDefinition> = {
  0: { id: "invalid", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
  1: { id: "push_i32", size: 5, nPop: 0, nPush: 1, format: OpFormat.i32 },
  2: { id: "push_const", size: 5, nPop: 0, nPush: 1, format: OpFormat.const },
  3: { id: "fclosure", size: 5, nPop: 0, nPush: 1, format: OpFormat.const },
  4: { id: "push_atom_value", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  5: { id: "private_symbol", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  6: { id: "undefined", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  7: { id: "null", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  8: { id: "push_this", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  9: { id: "push_false", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  10: { id: "push_true", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  11: { id: "object", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  12: { id: "special_object", size: 2, nPop: 0, nPush: 1, format: OpFormat.u8 },
  13: { id: "rest", size: 3, nPop: 0, nPush: 1, format: OpFormat.u16 },
  14: { id: "drop", size: 1, nPop: 1, nPush: 0, format: OpFormat.none },
  15: { id: "nip", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  16: { id: "nip1", size: 1, nPop: 3, nPush: 2, format: OpFormat.none },
  17: { id: "dup", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  18: { id: "dup1", size: 1, nPop: 2, nPush: 3, format: OpFormat.none },
  19: { id: "dup2", size: 1, nPop: 2, nPush: 4, format: OpFormat.none },
  20: { id: "dup3", size: 1, nPop: 3, nPush: 6, format: OpFormat.none },
  21: { id: "insert2", size: 1, nPop: 2, nPush: 3, format: OpFormat.none },
  22: { id: "insert3", size: 1, nPop: 3, nPush: 4, format: OpFormat.none },
  23: { id: "insert4", size: 1, nPop: 4, nPush: 5, format: OpFormat.none },
  24: { id: "perm3", size: 1, nPop: 3, nPush: 3, format: OpFormat.none },
  25: { id: "perm4", size: 1, nPop: 4, nPush: 4, format: OpFormat.none },
  26: { id: "perm5", size: 1, nPop: 5, nPush: 5, format: OpFormat.none },
  27: { id: "swap", size: 1, nPop: 2, nPush: 2, format: OpFormat.none },
  28: { id: "swap2", size: 1, nPop: 4, nPush: 4, format: OpFormat.none },
  29: { id: "rot3l", size: 1, nPop: 3, nPush: 3, format: OpFormat.none },
  30: { id: "rot3r", size: 1, nPop: 3, nPush: 3, format: OpFormat.none },
  31: { id: "rot4l", size: 1, nPop: 4, nPush: 4, format: OpFormat.none },
  32: { id: "rot5l", size: 1, nPop: 5, nPush: 5, format: OpFormat.none },
  33: { id: "call_constructor", size: 3, nPop: 2, nPush: 1, format: OpFormat.npop },
  34: { id: "call", size: 3, nPop: 1, nPush: 1, format: OpFormat.npop },
  35: { id: "tail_call", size: 3, nPop: 1, nPush: 0, format: OpFormat.npop },
  36: { id: "call_method", size: 3, nPop: 2, nPush: 1, format: OpFormat.npop },
  37: { id: "tail_call_method", size: 3, nPop: 2, nPush: 0, format: OpFormat.npop },
  38: { id: "array_from", size: 3, nPop: 0, nPush: 1, format: OpFormat.npop },
  39: { id: "apply", size: 3, nPop: 3, nPush: 1, format: OpFormat.u16 },
  40: { id: "return", size: 1, nPop: 1, nPush: 0, format: OpFormat.none },
  41: { id: "return_undef", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
  42: { id: "check_ctor_return", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  43: { id: "check_ctor", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
  44: { id: "init_ctor", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  45: { id: "check_brand", size: 1, nPop: 2, nPush: 2, format: OpFormat.none },
  46: { id: "add_brand", size: 1, nPop: 2, nPush: 0, format: OpFormat.none },
  47: { id: "return_async", size: 1, nPop: 1, nPush: 0, format: OpFormat.none },
  48: { id: "throw", size: 1, nPop: 1, nPush: 0, format: OpFormat.none },
  49: { id: "throw_error", size: 6, nPop: 0, nPush: 0, format: OpFormat.atom_u8 },
  50: { id: "eval", size: 5, nPop: 1, nPush: 1, format: OpFormat.npop_u16 },
  51: { id: "apply_eval", size: 3, nPop: 2, nPush: 1, format: OpFormat.u16 },
  52: { id: "regexp", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  53: { id: "get_super", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  54: { id: "import", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  55: { id: "check_var", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  56: { id: "get_var_undef", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  57: { id: "get_var", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  58: { id: "put_var", size: 5, nPop: 1, nPush: 0, format: OpFormat.atom },
  59: { id: "put_var_init", size: 5, nPop: 1, nPush: 0, format: OpFormat.atom },
  60: { id: "put_var_strict", size: 5, nPop: 2, nPush: 0, format: OpFormat.atom },
  61: { id: "get_ref_value", size: 1, nPop: 2, nPush: 3, format: OpFormat.none },
  62: { id: "put_ref_value", size: 1, nPop: 3, nPush: 0, format: OpFormat.none },
  63: { id: "define_var", size: 6, nPop: 0, nPush: 0, format: OpFormat.atom_u8 },
  64: { id: "check_define_var", size: 6, nPop: 0, nPush: 0, format: OpFormat.atom_u8 },
  65: { id: "define_func", size: 6, nPop: 1, nPush: 0, format: OpFormat.atom_u8 },
  66: { id: "get_field", size: 5, nPop: 1, nPush: 1, format: OpFormat.atom },
  67: { id: "get_field2", size: 5, nPop: 1, nPush: 2, format: OpFormat.atom },
  68: { id: "put_field", size: 5, nPop: 2, nPush: 0, format: OpFormat.atom },
  69: { id: "get_private_field", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  70: { id: "put_private_field", size: 1, nPop: 3, nPush: 0, format: OpFormat.none },
  71: { id: "define_private_field", size: 1, nPop: 3, nPush: 1, format: OpFormat.none },
  72: { id: "get_array_el", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  73: { id: "get_array_el2", size: 1, nPop: 2, nPush: 2, format: OpFormat.none },
  74: { id: "get_array_el3", size: 1, nPop: 2, nPush: 3, format: OpFormat.none },
  75: { id: "put_array_el", size: 1, nPop: 3, nPush: 0, format: OpFormat.none },
  76: { id: "get_super_value", size: 1, nPop: 3, nPush: 1, format: OpFormat.none },
  77: { id: "put_super_value", size: 1, nPop: 4, nPush: 0, format: OpFormat.none },
  78: { id: "define_field", size: 5, nPop: 2, nPush: 1, format: OpFormat.atom },
  79: { id: "set_name", size: 5, nPop: 1, nPush: 1, format: OpFormat.atom },
  80: { id: "set_name_computed", size: 1, nPop: 2, nPush: 2, format: OpFormat.none },
  81: { id: "set_proto", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  82: { id: "set_home_object", size: 1, nPop: 2, nPush: 2, format: OpFormat.none },
  83: { id: "define_array_el", size: 1, nPop: 3, nPush: 2, format: OpFormat.none },
  84: { id: "append", size: 1, nPop: 3, nPush: 2, format: OpFormat.none },
  85: { id: "copy_data_properties", size: 2, nPop: 3, nPush: 3, format: OpFormat.u8 },
  86: { id: "define_method", size: 6, nPop: 2, nPush: 1, format: OpFormat.atom_u8 },
  87: { id: "define_method_computed", size: 2, nPop: 3, nPush: 1, format: OpFormat.u8 },
  88: { id: "define_class", size: 6, nPop: 2, nPush: 2, format: OpFormat.atom_u8 },
  89: { id: "define_class_computed", size: 6, nPop: 3, nPush: 3, format: OpFormat.atom_u8 },
  90: { id: "get_loc", size: 3, nPop: 0, nPush: 1, format: OpFormat.loc },
  91: { id: "put_loc", size: 3, nPop: 1, nPush: 0, format: OpFormat.loc },
  92: { id: "set_loc", size: 3, nPop: 1, nPush: 1, format: OpFormat.loc },
  93: { id: "get_arg", size: 3, nPop: 0, nPush: 1, format: OpFormat.arg },
  94: { id: "put_arg", size: 3, nPop: 1, nPush: 0, format: OpFormat.arg },
  95: { id: "set_arg", size: 3, nPop: 1, nPush: 1, format: OpFormat.arg },
  96: { id: "get_var_ref", size: 3, nPop: 0, nPush: 1, format: OpFormat.var_ref },
  97: { id: "put_var_ref", size: 3, nPop: 1, nPush: 0, format: OpFormat.var_ref },
  98: { id: "set_var_ref", size: 3, nPop: 1, nPush: 1, format: OpFormat.var_ref },
  99: { id: "set_loc_uninitialized", size: 3, nPop: 0, nPush: 0, format: OpFormat.loc },
  100: { id: "get_loc_check", size: 3, nPop: 0, nPush: 1, format: OpFormat.loc },
  101: { id: "put_loc_check", size: 3, nPop: 1, nPush: 0, format: OpFormat.loc },
  102: { id: "put_loc_check_init", size: 3, nPop: 1, nPush: 0, format: OpFormat.loc },
  103: { id: "get_loc_checkthis", size: 3, nPop: 0, nPush: 1, format: OpFormat.loc },
  104: { id: "get_var_ref_check", size: 3, nPop: 0, nPush: 1, format: OpFormat.var_ref },
  105: { id: "put_var_ref_check", size: 3, nPop: 1, nPush: 0, format: OpFormat.var_ref },
  106: { id: "put_var_ref_check_init", size: 3, nPop: 1, nPush: 0, format: OpFormat.var_ref },
  107: { id: "close_loc", size: 3, nPop: 0, nPush: 0, format: OpFormat.loc },
  108: { id: "if_false", size: 5, nPop: 1, nPush: 0, format: OpFormat.label },
  109: { id: "if_true", size: 5, nPop: 1, nPush: 0, format: OpFormat.label },
  110: { id: "goto", size: 5, nPop: 0, nPush: 0, format: OpFormat.label },
  111: { id: "catch", size: 5, nPop: 0, nPush: 1, format: OpFormat.label },
  112: { id: "gosub", size: 5, nPop: 0, nPush: 0, format: OpFormat.label },
  113: { id: "ret", size: 1, nPop: 1, nPush: 0, format: OpFormat.none },
  114: { id: "nip_catch", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  115: { id: "to_object", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  116: { id: "to_propkey", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  117: { id: "with_get_var", size: 10, nPop: 1, nPush: 0, format: OpFormat.atom_label_u8 },
  118: { id: "with_put_var", size: 10, nPop: 2, nPush: 1, format: OpFormat.atom_label_u8 },
  119: { id: "with_delete_var", size: 10, nPop: 1, nPush: 0, format: OpFormat.atom_label_u8 },
  120: { id: "with_make_ref", size: 10, nPop: 1, nPush: 0, format: OpFormat.atom_label_u8 },
  121: { id: "with_get_ref", size: 10, nPop: 1, nPush: 0, format: OpFormat.atom_label_u8 },
  122: { id: "make_loc_ref", size: 7, nPop: 0, nPush: 2, format: OpFormat.atom_u16 },
  123: { id: "make_arg_ref", size: 7, nPop: 0, nPush: 2, format: OpFormat.atom_u16 },
  124: { id: "make_var_ref_ref", size: 7, nPop: 0, nPush: 2, format: OpFormat.atom_u16 },
  125: { id: "make_var_ref", size: 5, nPop: 0, nPush: 2, format: OpFormat.atom },
  126: { id: "for_in_start", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  127: { id: "for_of_start", size: 1, nPop: 1, nPush: 3, format: OpFormat.none },
  128: { id: "for_await_of_start", size: 1, nPop: 1, nPush: 3, format: OpFormat.none },
  129: { id: "for_in_next", size: 1, nPop: 1, nPush: 3, format: OpFormat.none },
  130: { id: "for_of_next", size: 2, nPop: 3, nPush: 5, format: OpFormat.u8 },
  131: { id: "for_await_of_next", size: 1, nPop: 3, nPush: 4, format: OpFormat.none },
  132: { id: "iterator_check_object", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  133: { id: "iterator_get_value_done", size: 1, nPop: 2, nPush: 3, format: OpFormat.none },
  134: { id: "iterator_close", size: 1, nPop: 3, nPush: 0, format: OpFormat.none },
  135: { id: "iterator_next", size: 1, nPop: 4, nPush: 4, format: OpFormat.none },
  136: { id: "iterator_call", size: 2, nPop: 4, nPush: 5, format: OpFormat.u8 },
  137: { id: "initial_yield", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
  138: { id: "yield", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  139: { id: "yield_star", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  140: { id: "async_yield_star", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  141: { id: "await", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  142: { id: "neg", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  143: { id: "plus", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  144: { id: "dec", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  145: { id: "inc", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  146: { id: "post_dec", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  147: { id: "post_inc", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  148: { id: "dec_loc", size: 2, nPop: 0, nPush: 0, format: OpFormat.loc8 },
  149: { id: "inc_loc", size: 2, nPop: 0, nPush: 0, format: OpFormat.loc8 },
  150: { id: "add_loc", size: 2, nPop: 1, nPush: 0, format: OpFormat.loc8 },
  151: { id: "not", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  152: { id: "lnot", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  153: { id: "typeof", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  154: { id: "delete", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  155: { id: "delete_var", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  156: { id: "mul", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  157: { id: "div", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  158: { id: "mod", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  159: { id: "add", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  160: { id: "sub", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  161: { id: "pow", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  162: { id: "shl", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  163: { id: "sar", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  164: { id: "shr", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  165: { id: "lt", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  166: { id: "lte", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  167: { id: "gt", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  168: { id: "gte", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  169: { id: "instanceof", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  170: { id: "in", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  171: { id: "eq", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  172: { id: "neq", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  173: { id: "strict_eq", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  174: { id: "strict_neq", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  175: { id: "and", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  176: { id: "xor", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  177: { id: "or", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  178: { id: "is_undefined_or_null", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  179: { id: "private_in", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  180: { id: "push_bigint_i32", size: 5, nPop: 0, nPush: 1, format: OpFormat.i32 },
  181: { id: "nop", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
  182: { id: "push_minus1", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  183: { id: "push_0", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  184: { id: "push_1", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  185: { id: "push_2", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  186: { id: "push_3", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  187: { id: "push_4", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  188: { id: "push_5", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  189: { id: "push_6", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  190: { id: "push_7", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  191: { id: "push_i8", size: 2, nPop: 0, nPush: 1, format: OpFormat.i8 },
  192: { id: "push_i16", size: 3, nPop: 0, nPush: 1, format: OpFormat.i16 },
  193: { id: "push_const8", size: 2, nPop: 0, nPush: 1, format: OpFormat.const8 },
  194: { id: "fclosure8", size: 2, nPop: 0, nPush: 1, format: OpFormat.const8 },
  195: { id: "push_empty_string", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  196: { id: "get_loc8", size: 2, nPop: 0, nPush: 1, format: OpFormat.loc8 },
  197: { id: "put_loc8", size: 2, nPop: 1, nPush: 0, format: OpFormat.loc8 },
  198: { id: "set_loc8", size: 2, nPop: 1, nPush: 1, format: OpFormat.loc8 },
  199: { id: "get_loc0", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_loc },
  200: { id: "get_loc1", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_loc },
  201: { id: "get_loc2", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_loc },
  202: { id: "get_loc3", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_loc },
  203: { id: "put_loc0", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_loc },
  204: { id: "put_loc1", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_loc },
  205: { id: "put_loc2", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_loc },
  206: { id: "put_loc3", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_loc },
  207: { id: "set_loc0", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_loc },
  208: { id: "set_loc1", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_loc },
  209: { id: "set_loc2", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_loc },
  210: { id: "set_loc3", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_loc },
  211: { id: "get_arg0", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_arg },
  212: { id: "get_arg1", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_arg },
  213: { id: "get_arg2", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_arg },
  214: { id: "get_arg3", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_arg },
  215: { id: "put_arg0", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_arg },
  216: { id: "put_arg1", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_arg },
  217: { id: "put_arg2", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_arg },
  218: { id: "put_arg3", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_arg },
  219: { id: "set_arg0", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_arg },
  220: { id: "set_arg1", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_arg },
  221: { id: "set_arg2", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_arg },
  222: { id: "set_arg3", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_arg },
  223: { id: "get_var_ref0", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_var_ref },
  224: { id: "get_var_ref1", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_var_ref },
  225: { id: "get_var_ref2", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_var_ref },
  226: { id: "get_var_ref3", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_var_ref },
  227: { id: "put_var_ref0", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_var_ref },
  228: { id: "put_var_ref1", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_var_ref },
  229: { id: "put_var_ref2", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_var_ref },
  230: { id: "put_var_ref3", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_var_ref },
  231: { id: "set_var_ref0", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_var_ref },
  232: { id: "set_var_ref1", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_var_ref },
  233: { id: "set_var_ref2", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_var_ref },
  234: { id: "set_var_ref3", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_var_ref },
  235: { id: "get_length", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  236: { id: "if_false8", size: 2, nPop: 1, nPush: 0, format: OpFormat.label8 },
  237: { id: "if_true8", size: 2, nPop: 1, nPush: 0, format: OpFormat.label8 },
  238: { id: "goto8", size: 2, nPop: 0, nPush: 0, format: OpFormat.label8 },
  239: { id: "goto16", size: 3, nPop: 0, nPush: 0, format: OpFormat.label16 },
  240: { id: "call0", size: 1, nPop: 1, nPush: 1, format: OpFormat.npopx },
  241: { id: "call1", size: 1, nPop: 1, nPush: 1, format: OpFormat.npopx },
  242: { id: "call2", size: 1, nPop: 1, nPush: 1, format: OpFormat.npopx },
  243: { id: "call3", size: 1, nPop: 1, nPush: 1, format: OpFormat.npopx },
  244: { id: "is_undefined", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  245: { id: "is_null", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  246: { id: "typeof_is_undefined", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  247: { id: "typeof_is_function", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  248: { id: "get_field_ic", size: 5, nPop: 1, nPush: 1, format: OpFormat.none },
  249: { id: "get_field2_ic", size: 5, nPop: 1, nPush: 2, format: OpFormat.none },
  250: { id: "put_field_ic", size: 5, nPop: 2, nPush: 0, format: OpFormat.none },
  251: { id: "debugger", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
}

// 临时 opcodes: 只在编译阶段使用，不会出现在最终字节码中
export const TEMP_OPCODE_DEFS: Record<string, OpcodeDefinition> = {
  OP_enter_scope: { id: "enter_scope", size: 3, nPop: 0, nPush: 0, format: OpFormat.u16 },
  OP_leave_scope: { id: "leave_scope", size: 3, nPop: 0, nPush: 0, format: OpFormat.u16 },
  OP_label: { id: "label", size: 5, nPop: 0, nPush: 0, format: OpFormat.label },
  OP_scope_get_var_undef: { id: "scope_get_var_undef", size: 7, nPop: 0, nPush: 1, format: OpFormat.atom_u16 },
  OP_scope_get_var: { id: "scope_get_var", size: 7, nPop: 0, nPush: 1, format: OpFormat.atom_u16 },
  OP_scope_put_var: { id: "scope_put_var", size: 7, nPop: 1, nPush: 0, format: OpFormat.atom_u16 },
  OP_scope_delete_var: { id: "scope_delete_var", size: 7, nPop: 0, nPush: 1, format: OpFormat.atom_u16 },
  OP_scope_make_ref: { id: "scope_make_ref", size: 11, nPop: 0, nPush: 2, format: OpFormat.atom_label_u16 },
  OP_scope_get_ref: { id: "scope_get_ref", size: 7, nPop: 0, nPush: 2, format: OpFormat.atom_u16 },
  OP_scope_put_var_init: { id: "scope_put_var_init", size: 7, nPop: 0, nPush: 2, format: OpFormat.atom_u16 },
  OP_scope_get_var_checkthis: { id: "scope_get_var_checkthis", size: 7, nPop: 0, nPush: 1, format: OpFormat.atom_u16 },
  OP_scope_get_private_field: { id: "scope_get_private_field", size: 7, nPop: 1, nPush: 1, format: OpFormat.atom_u16 },
  OP_scope_get_private_field2: { id: "scope_get_private_field2", size: 7, nPop: 1, nPush: 2, format: OpFormat.atom_u16 },
  OP_scope_put_private_field: { id: "scope_put_private_field", size: 7, nPop: 2, nPush: 0, format: OpFormat.atom_u16 },
  OP_scope_in_private_field: { id: "scope_in_private_field", size: 7, nPop: 1, nPush: 1, format: OpFormat.atom_u16 },
  OP_get_field_opt_chain: { id: "get_field_opt_chain", size: 5, nPop: 1, nPush: 1, format: OpFormat.atom },
  OP_get_array_el_opt_chain: { id: "get_array_el_opt_chain", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_set_class_name: { id: "set_class_name", size: 5, nPop: 1, nPush: 1, format: OpFormat.u32 },
  OP_line_num: { id: "line_num", size: 5, nPop: 0, nPush: 0, format: OpFormat.u32 },
}

export const TEMP_OPCODE_BY_CODE: Record<number, OpcodeDefinition> = {
  182: { id: "enter_scope", size: 3, nPop: 0, nPush: 0, format: OpFormat.u16 },
  183: { id: "leave_scope", size: 3, nPop: 0, nPush: 0, format: OpFormat.u16 },
  184: { id: "label", size: 5, nPop: 0, nPush: 0, format: OpFormat.label },
  185: { id: "scope_get_var_undef", size: 7, nPop: 0, nPush: 1, format: OpFormat.atom_u16 },
  186: { id: "scope_get_var", size: 7, nPop: 0, nPush: 1, format: OpFormat.atom_u16 },
  187: { id: "scope_put_var", size: 7, nPop: 1, nPush: 0, format: OpFormat.atom_u16 },
  188: { id: "scope_delete_var", size: 7, nPop: 0, nPush: 1, format: OpFormat.atom_u16 },
  189: { id: "scope_make_ref", size: 11, nPop: 0, nPush: 2, format: OpFormat.atom_label_u16 },
  190: { id: "scope_get_ref", size: 7, nPop: 0, nPush: 2, format: OpFormat.atom_u16 },
  191: { id: "scope_put_var_init", size: 7, nPop: 0, nPush: 2, format: OpFormat.atom_u16 },
  192: { id: "scope_get_var_checkthis", size: 7, nPop: 0, nPush: 1, format: OpFormat.atom_u16 },
  193: { id: "scope_get_private_field", size: 7, nPop: 1, nPush: 1, format: OpFormat.atom_u16 },
  194: { id: "scope_get_private_field2", size: 7, nPop: 1, nPush: 2, format: OpFormat.atom_u16 },
  195: { id: "scope_put_private_field", size: 7, nPop: 2, nPush: 0, format: OpFormat.atom_u16 },
  196: { id: "scope_in_private_field", size: 7, nPop: 1, nPush: 1, format: OpFormat.atom_u16 },
  197: { id: "get_field_opt_chain", size: 5, nPop: 1, nPush: 1, format: OpFormat.atom },
  198: { id: "get_array_el_opt_chain", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  199: { id: "set_class_name", size: 5, nPop: 1, nPush: 1, format: OpFormat.u32 },
  200: { id: "line_num", size: 5, nPop: 0, nPush: 0, format: OpFormat.u32 },
}

export const SHORT_OPCODE_DEFS: Record<string, OpcodeDefinition> = {
  OP_invalid: { id: "invalid", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
  OP_push_i32: { id: "push_i32", size: 5, nPop: 0, nPush: 1, format: OpFormat.i32 },
  OP_push_const: { id: "push_const", size: 5, nPop: 0, nPush: 1, format: OpFormat.const },
  OP_fclosure: { id: "fclosure", size: 5, nPop: 0, nPush: 1, format: OpFormat.const },
  OP_push_atom_value: { id: "push_atom_value", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  OP_private_symbol: { id: "private_symbol", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  OP_undefined: { id: "undefined", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_null: { id: "null", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_push_this: { id: "push_this", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_push_false: { id: "push_false", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_push_true: { id: "push_true", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_object: { id: "object", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_special_object: { id: "special_object", size: 2, nPop: 0, nPush: 1, format: OpFormat.u8 },
  OP_rest: { id: "rest", size: 3, nPop: 0, nPush: 1, format: OpFormat.u16 },
  OP_drop: { id: "drop", size: 1, nPop: 1, nPush: 0, format: OpFormat.none },
  OP_nip: { id: "nip", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_nip1: { id: "nip1", size: 1, nPop: 3, nPush: 2, format: OpFormat.none },
  OP_dup: { id: "dup", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_dup1: { id: "dup1", size: 1, nPop: 2, nPush: 3, format: OpFormat.none },
  OP_dup2: { id: "dup2", size: 1, nPop: 2, nPush: 4, format: OpFormat.none },
  OP_dup3: { id: "dup3", size: 1, nPop: 3, nPush: 6, format: OpFormat.none },
  OP_insert2: { id: "insert2", size: 1, nPop: 2, nPush: 3, format: OpFormat.none },
  OP_insert3: { id: "insert3", size: 1, nPop: 3, nPush: 4, format: OpFormat.none },
  OP_insert4: { id: "insert4", size: 1, nPop: 4, nPush: 5, format: OpFormat.none },
  OP_perm3: { id: "perm3", size: 1, nPop: 3, nPush: 3, format: OpFormat.none },
  OP_perm4: { id: "perm4", size: 1, nPop: 4, nPush: 4, format: OpFormat.none },
  OP_perm5: { id: "perm5", size: 1, nPop: 5, nPush: 5, format: OpFormat.none },
  OP_swap: { id: "swap", size: 1, nPop: 2, nPush: 2, format: OpFormat.none },
  OP_swap2: { id: "swap2", size: 1, nPop: 4, nPush: 4, format: OpFormat.none },
  OP_rot3l: { id: "rot3l", size: 1, nPop: 3, nPush: 3, format: OpFormat.none },
  OP_rot3r: { id: "rot3r", size: 1, nPop: 3, nPush: 3, format: OpFormat.none },
  OP_rot4l: { id: "rot4l", size: 1, nPop: 4, nPush: 4, format: OpFormat.none },
  OP_rot5l: { id: "rot5l", size: 1, nPop: 5, nPush: 5, format: OpFormat.none },
  OP_call_constructor: { id: "call_constructor", size: 3, nPop: 2, nPush: 1, format: OpFormat.npop },
  OP_call: { id: "call", size: 3, nPop: 1, nPush: 1, format: OpFormat.npop },
  OP_tail_call: { id: "tail_call", size: 3, nPop: 1, nPush: 0, format: OpFormat.npop },
  OP_call_method: { id: "call_method", size: 3, nPop: 2, nPush: 1, format: OpFormat.npop },
  OP_tail_call_method: { id: "tail_call_method", size: 3, nPop: 2, nPush: 0, format: OpFormat.npop },
  OP_array_from: { id: "array_from", size: 3, nPop: 0, nPush: 1, format: OpFormat.npop },
  OP_apply: { id: "apply", size: 3, nPop: 3, nPush: 1, format: OpFormat.u16 },
  OP_return: { id: "return", size: 1, nPop: 1, nPush: 0, format: OpFormat.none },
  OP_return_undef: { id: "return_undef", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
  OP_check_ctor_return: { id: "check_ctor_return", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_check_ctor: { id: "check_ctor", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
  OP_init_ctor: { id: "init_ctor", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_check_brand: { id: "check_brand", size: 1, nPop: 2, nPush: 2, format: OpFormat.none },
  OP_add_brand: { id: "add_brand", size: 1, nPop: 2, nPush: 0, format: OpFormat.none },
  OP_return_async: { id: "return_async", size: 1, nPop: 1, nPush: 0, format: OpFormat.none },
  OP_throw: { id: "throw", size: 1, nPop: 1, nPush: 0, format: OpFormat.none },
  OP_throw_error: { id: "throw_error", size: 6, nPop: 0, nPush: 0, format: OpFormat.atom_u8 },
  OP_eval: { id: "eval", size: 5, nPop: 1, nPush: 1, format: OpFormat.npop_u16 },
  OP_apply_eval: { id: "apply_eval", size: 3, nPop: 2, nPush: 1, format: OpFormat.u16 },
  OP_regexp: { id: "regexp", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_get_super: { id: "get_super", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_import: { id: "import", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_check_var: { id: "check_var", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  OP_get_var_undef: { id: "get_var_undef", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  OP_get_var: { id: "get_var", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  OP_put_var: { id: "put_var", size: 5, nPop: 1, nPush: 0, format: OpFormat.atom },
  OP_put_var_init: { id: "put_var_init", size: 5, nPop: 1, nPush: 0, format: OpFormat.atom },
  OP_put_var_strict: { id: "put_var_strict", size: 5, nPop: 2, nPush: 0, format: OpFormat.atom },
  OP_get_ref_value: { id: "get_ref_value", size: 1, nPop: 2, nPush: 3, format: OpFormat.none },
  OP_put_ref_value: { id: "put_ref_value", size: 1, nPop: 3, nPush: 0, format: OpFormat.none },
  OP_define_var: { id: "define_var", size: 6, nPop: 0, nPush: 0, format: OpFormat.atom_u8 },
  OP_check_define_var: { id: "check_define_var", size: 6, nPop: 0, nPush: 0, format: OpFormat.atom_u8 },
  OP_define_func: { id: "define_func", size: 6, nPop: 1, nPush: 0, format: OpFormat.atom_u8 },
  OP_get_field: { id: "get_field", size: 5, nPop: 1, nPush: 1, format: OpFormat.atom },
  OP_get_field2: { id: "get_field2", size: 5, nPop: 1, nPush: 2, format: OpFormat.atom },
  OP_put_field: { id: "put_field", size: 5, nPop: 2, nPush: 0, format: OpFormat.atom },
  OP_get_private_field: { id: "get_private_field", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_put_private_field: { id: "put_private_field", size: 1, nPop: 3, nPush: 0, format: OpFormat.none },
  OP_define_private_field: { id: "define_private_field", size: 1, nPop: 3, nPush: 1, format: OpFormat.none },
  OP_get_array_el: { id: "get_array_el", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_get_array_el2: { id: "get_array_el2", size: 1, nPop: 2, nPush: 2, format: OpFormat.none },
  OP_get_array_el3: { id: "get_array_el3", size: 1, nPop: 2, nPush: 3, format: OpFormat.none },
  OP_put_array_el: { id: "put_array_el", size: 1, nPop: 3, nPush: 0, format: OpFormat.none },
  OP_get_super_value: { id: "get_super_value", size: 1, nPop: 3, nPush: 1, format: OpFormat.none },
  OP_put_super_value: { id: "put_super_value", size: 1, nPop: 4, nPush: 0, format: OpFormat.none },
  OP_define_field: { id: "define_field", size: 5, nPop: 2, nPush: 1, format: OpFormat.atom },
  OP_set_name: { id: "set_name", size: 5, nPop: 1, nPush: 1, format: OpFormat.atom },
  OP_set_name_computed: { id: "set_name_computed", size: 1, nPop: 2, nPush: 2, format: OpFormat.none },
  OP_set_proto: { id: "set_proto", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_set_home_object: { id: "set_home_object", size: 1, nPop: 2, nPush: 2, format: OpFormat.none },
  OP_define_array_el: { id: "define_array_el", size: 1, nPop: 3, nPush: 2, format: OpFormat.none },
  OP_append: { id: "append", size: 1, nPop: 3, nPush: 2, format: OpFormat.none },
  OP_copy_data_properties: { id: "copy_data_properties", size: 2, nPop: 3, nPush: 3, format: OpFormat.u8 },
  OP_define_method: { id: "define_method", size: 6, nPop: 2, nPush: 1, format: OpFormat.atom_u8 },
  OP_define_method_computed: { id: "define_method_computed", size: 2, nPop: 3, nPush: 1, format: OpFormat.u8 },
  OP_define_class: { id: "define_class", size: 6, nPop: 2, nPush: 2, format: OpFormat.atom_u8 },
  OP_define_class_computed: { id: "define_class_computed", size: 6, nPop: 3, nPush: 3, format: OpFormat.atom_u8 },
  OP_get_loc: { id: "get_loc", size: 3, nPop: 0, nPush: 1, format: OpFormat.loc },
  OP_put_loc: { id: "put_loc", size: 3, nPop: 1, nPush: 0, format: OpFormat.loc },
  OP_set_loc: { id: "set_loc", size: 3, nPop: 1, nPush: 1, format: OpFormat.loc },
  OP_get_arg: { id: "get_arg", size: 3, nPop: 0, nPush: 1, format: OpFormat.arg },
  OP_put_arg: { id: "put_arg", size: 3, nPop: 1, nPush: 0, format: OpFormat.arg },
  OP_set_arg: { id: "set_arg", size: 3, nPop: 1, nPush: 1, format: OpFormat.arg },
  OP_get_var_ref: { id: "get_var_ref", size: 3, nPop: 0, nPush: 1, format: OpFormat.var_ref },
  OP_put_var_ref: { id: "put_var_ref", size: 3, nPop: 1, nPush: 0, format: OpFormat.var_ref },
  OP_set_var_ref: { id: "set_var_ref", size: 3, nPop: 1, nPush: 1, format: OpFormat.var_ref },
  OP_set_loc_uninitialized: { id: "set_loc_uninitialized", size: 3, nPop: 0, nPush: 0, format: OpFormat.loc },
  OP_get_loc_check: { id: "get_loc_check", size: 3, nPop: 0, nPush: 1, format: OpFormat.loc },
  OP_put_loc_check: { id: "put_loc_check", size: 3, nPop: 1, nPush: 0, format: OpFormat.loc },
  OP_put_loc_check_init: { id: "put_loc_check_init", size: 3, nPop: 1, nPush: 0, format: OpFormat.loc },
  OP_get_loc_checkthis: { id: "get_loc_checkthis", size: 3, nPop: 0, nPush: 1, format: OpFormat.loc },
  OP_get_var_ref_check: { id: "get_var_ref_check", size: 3, nPop: 0, nPush: 1, format: OpFormat.var_ref },
  OP_put_var_ref_check: { id: "put_var_ref_check", size: 3, nPop: 1, nPush: 0, format: OpFormat.var_ref },
  OP_put_var_ref_check_init: { id: "put_var_ref_check_init", size: 3, nPop: 1, nPush: 0, format: OpFormat.var_ref },
  OP_close_loc: { id: "close_loc", size: 3, nPop: 0, nPush: 0, format: OpFormat.loc },
  OP_if_false: { id: "if_false", size: 5, nPop: 1, nPush: 0, format: OpFormat.label },
  OP_if_true: { id: "if_true", size: 5, nPop: 1, nPush: 0, format: OpFormat.label },
  OP_goto: { id: "goto", size: 5, nPop: 0, nPush: 0, format: OpFormat.label },
  OP_catch: { id: "catch", size: 5, nPop: 0, nPush: 1, format: OpFormat.label },
  OP_gosub: { id: "gosub", size: 5, nPop: 0, nPush: 0, format: OpFormat.label },
  OP_ret: { id: "ret", size: 1, nPop: 1, nPush: 0, format: OpFormat.none },
  OP_nip_catch: { id: "nip_catch", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_to_object: { id: "to_object", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_to_propkey: { id: "to_propkey", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_with_get_var: { id: "with_get_var", size: 10, nPop: 1, nPush: 0, format: OpFormat.atom_label_u8 },
  OP_with_put_var: { id: "with_put_var", size: 10, nPop: 2, nPush: 1, format: OpFormat.atom_label_u8 },
  OP_with_delete_var: { id: "with_delete_var", size: 10, nPop: 1, nPush: 0, format: OpFormat.atom_label_u8 },
  OP_with_make_ref: { id: "with_make_ref", size: 10, nPop: 1, nPush: 0, format: OpFormat.atom_label_u8 },
  OP_with_get_ref: { id: "with_get_ref", size: 10, nPop: 1, nPush: 0, format: OpFormat.atom_label_u8 },
  OP_make_loc_ref: { id: "make_loc_ref", size: 7, nPop: 0, nPush: 2, format: OpFormat.atom_u16 },
  OP_make_arg_ref: { id: "make_arg_ref", size: 7, nPop: 0, nPush: 2, format: OpFormat.atom_u16 },
  OP_make_var_ref_ref: { id: "make_var_ref_ref", size: 7, nPop: 0, nPush: 2, format: OpFormat.atom_u16 },
  OP_make_var_ref: { id: "make_var_ref", size: 5, nPop: 0, nPush: 2, format: OpFormat.atom },
  OP_for_in_start: { id: "for_in_start", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_for_of_start: { id: "for_of_start", size: 1, nPop: 1, nPush: 3, format: OpFormat.none },
  OP_for_await_of_start: { id: "for_await_of_start", size: 1, nPop: 1, nPush: 3, format: OpFormat.none },
  OP_for_in_next: { id: "for_in_next", size: 1, nPop: 1, nPush: 3, format: OpFormat.none },
  OP_for_of_next: { id: "for_of_next", size: 2, nPop: 3, nPush: 5, format: OpFormat.u8 },
  OP_for_await_of_next: { id: "for_await_of_next", size: 1, nPop: 3, nPush: 4, format: OpFormat.none },
  OP_iterator_check_object: { id: "iterator_check_object", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_iterator_get_value_done: { id: "iterator_get_value_done", size: 1, nPop: 2, nPush: 3, format: OpFormat.none },
  OP_iterator_close: { id: "iterator_close", size: 1, nPop: 3, nPush: 0, format: OpFormat.none },
  OP_iterator_next: { id: "iterator_next", size: 1, nPop: 4, nPush: 4, format: OpFormat.none },
  OP_iterator_call: { id: "iterator_call", size: 2, nPop: 4, nPush: 5, format: OpFormat.u8 },
  OP_initial_yield: { id: "initial_yield", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
  OP_yield: { id: "yield", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_yield_star: { id: "yield_star", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_async_yield_star: { id: "async_yield_star", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_await: { id: "await", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_neg: { id: "neg", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_plus: { id: "plus", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_dec: { id: "dec", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_inc: { id: "inc", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_post_dec: { id: "post_dec", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_post_inc: { id: "post_inc", size: 1, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_dec_loc: { id: "dec_loc", size: 2, nPop: 0, nPush: 0, format: OpFormat.loc8 },
  OP_inc_loc: { id: "inc_loc", size: 2, nPop: 0, nPush: 0, format: OpFormat.loc8 },
  OP_add_loc: { id: "add_loc", size: 2, nPop: 1, nPush: 0, format: OpFormat.loc8 },
  OP_not: { id: "not", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_lnot: { id: "lnot", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_typeof: { id: "typeof", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_delete: { id: "delete", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_delete_var: { id: "delete_var", size: 5, nPop: 0, nPush: 1, format: OpFormat.atom },
  OP_mul: { id: "mul", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_div: { id: "div", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_mod: { id: "mod", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_add: { id: "add", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_sub: { id: "sub", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_pow: { id: "pow", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_shl: { id: "shl", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_sar: { id: "sar", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_shr: { id: "shr", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_lt: { id: "lt", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_lte: { id: "lte", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_gt: { id: "gt", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_gte: { id: "gte", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_instanceof: { id: "instanceof", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_in: { id: "in", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_eq: { id: "eq", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_neq: { id: "neq", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_strict_eq: { id: "strict_eq", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_strict_neq: { id: "strict_neq", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_and: { id: "and", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_xor: { id: "xor", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_or: { id: "or", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_is_undefined_or_null: { id: "is_undefined_or_null", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_private_in: { id: "private_in", size: 1, nPop: 2, nPush: 1, format: OpFormat.none },
  OP_push_bigint_i32: { id: "push_bigint_i32", size: 5, nPop: 0, nPush: 1, format: OpFormat.i32 },
  OP_nop: { id: "nop", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
  OP_push_minus1: { id: "push_minus1", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_0: { id: "push_0", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_1: { id: "push_1", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_2: { id: "push_2", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_3: { id: "push_3", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_4: { id: "push_4", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_5: { id: "push_5", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_6: { id: "push_6", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_7: { id: "push_7", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_int },
  OP_push_i8: { id: "push_i8", size: 2, nPop: 0, nPush: 1, format: OpFormat.i8 },
  OP_push_i16: { id: "push_i16", size: 3, nPop: 0, nPush: 1, format: OpFormat.i16 },
  OP_push_const8: { id: "push_const8", size: 2, nPop: 0, nPush: 1, format: OpFormat.const8 },
  OP_fclosure8: { id: "fclosure8", size: 2, nPop: 0, nPush: 1, format: OpFormat.const8 },
  OP_push_empty_string: { id: "push_empty_string", size: 1, nPop: 0, nPush: 1, format: OpFormat.none },
  OP_get_loc8: { id: "get_loc8", size: 2, nPop: 0, nPush: 1, format: OpFormat.loc8 },
  OP_put_loc8: { id: "put_loc8", size: 2, nPop: 1, nPush: 0, format: OpFormat.loc8 },
  OP_set_loc8: { id: "set_loc8", size: 2, nPop: 1, nPush: 1, format: OpFormat.loc8 },
  OP_get_loc0: { id: "get_loc0", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_loc },
  OP_get_loc1: { id: "get_loc1", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_loc },
  OP_get_loc2: { id: "get_loc2", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_loc },
  OP_get_loc3: { id: "get_loc3", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_loc },
  OP_put_loc0: { id: "put_loc0", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_loc },
  OP_put_loc1: { id: "put_loc1", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_loc },
  OP_put_loc2: { id: "put_loc2", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_loc },
  OP_put_loc3: { id: "put_loc3", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_loc },
  OP_set_loc0: { id: "set_loc0", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_loc },
  OP_set_loc1: { id: "set_loc1", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_loc },
  OP_set_loc2: { id: "set_loc2", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_loc },
  OP_set_loc3: { id: "set_loc3", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_loc },
  OP_get_arg0: { id: "get_arg0", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_arg },
  OP_get_arg1: { id: "get_arg1", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_arg },
  OP_get_arg2: { id: "get_arg2", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_arg },
  OP_get_arg3: { id: "get_arg3", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_arg },
  OP_put_arg0: { id: "put_arg0", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_arg },
  OP_put_arg1: { id: "put_arg1", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_arg },
  OP_put_arg2: { id: "put_arg2", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_arg },
  OP_put_arg3: { id: "put_arg3", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_arg },
  OP_set_arg0: { id: "set_arg0", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_arg },
  OP_set_arg1: { id: "set_arg1", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_arg },
  OP_set_arg2: { id: "set_arg2", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_arg },
  OP_set_arg3: { id: "set_arg3", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_arg },
  OP_get_var_ref0: { id: "get_var_ref0", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_var_ref },
  OP_get_var_ref1: { id: "get_var_ref1", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_var_ref },
  OP_get_var_ref2: { id: "get_var_ref2", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_var_ref },
  OP_get_var_ref3: { id: "get_var_ref3", size: 1, nPop: 0, nPush: 1, format: OpFormat.none_var_ref },
  OP_put_var_ref0: { id: "put_var_ref0", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_var_ref },
  OP_put_var_ref1: { id: "put_var_ref1", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_var_ref },
  OP_put_var_ref2: { id: "put_var_ref2", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_var_ref },
  OP_put_var_ref3: { id: "put_var_ref3", size: 1, nPop: 1, nPush: 0, format: OpFormat.none_var_ref },
  OP_set_var_ref0: { id: "set_var_ref0", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_var_ref },
  OP_set_var_ref1: { id: "set_var_ref1", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_var_ref },
  OP_set_var_ref2: { id: "set_var_ref2", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_var_ref },
  OP_set_var_ref3: { id: "set_var_ref3", size: 1, nPop: 1, nPush: 1, format: OpFormat.none_var_ref },
  OP_get_length: { id: "get_length", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_if_false8: { id: "if_false8", size: 2, nPop: 1, nPush: 0, format: OpFormat.label8 },
  OP_if_true8: { id: "if_true8", size: 2, nPop: 1, nPush: 0, format: OpFormat.label8 },
  OP_goto8: { id: "goto8", size: 2, nPop: 0, nPush: 0, format: OpFormat.label8 },
  OP_goto16: { id: "goto16", size: 3, nPop: 0, nPush: 0, format: OpFormat.label16 },
  OP_call0: { id: "call0", size: 1, nPop: 1, nPush: 1, format: OpFormat.npopx },
  OP_call1: { id: "call1", size: 1, nPop: 1, nPush: 1, format: OpFormat.npopx },
  OP_call2: { id: "call2", size: 1, nPop: 1, nPush: 1, format: OpFormat.npopx },
  OP_call3: { id: "call3", size: 1, nPop: 1, nPush: 1, format: OpFormat.npopx },
  OP_is_undefined: { id: "is_undefined", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_is_null: { id: "is_null", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_typeof_is_undefined: { id: "typeof_is_undefined", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_typeof_is_function: { id: "typeof_is_function", size: 1, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_get_field_ic: { id: "get_field_ic", size: 5, nPop: 1, nPush: 1, format: OpFormat.none },
  OP_get_field2_ic: { id: "get_field2_ic", size: 5, nPop: 1, nPush: 2, format: OpFormat.none },
  OP_put_field_ic: { id: "put_field_ic", size: 5, nPop: 2, nPush: 0, format: OpFormat.none },
  OP_debugger: { id: "debugger", size: 1, nPop: 0, nPush: 0, format: OpFormat.none },
}

export interface Env {
  bytecodeVersion: number
  compileOptions: number
  firstAtomId: number
  supportsShortOpcodes: boolean
  globalVarOffset: number
  argumentVarOffset: number
  argScopeIndex: number
  argScopeEnd: number
  debugScopeIndex: number
  maxLocalVars: number
  stackSizeMax: number
}

export const env = {
  bytecodeVersion: 5,
  compileOptions: 5,
  firstAtomId: 228,
  supportsShortOpcodes: true,
  globalVarOffset: 1073741824,
  argumentVarOffset: 536870912,
  argScopeIndex: 1,
  argScopeEnd: -2,
  debugScopeIndex: -3,
  maxLocalVars: 65534,
  stackSizeMax: 65534,
} as const
